/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SmartContract } from './smartContract';
import { Wallet } from './wallet';

/**
* Represents detailed account information for a user.
*/
export class AccountEntity {
   'userId': string;
   'name'?: string;
   'email'?: string;
   'wallets'?: Array<Wallet>;
   'smartContracts'?: Array<SmartContract>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "wallets",
            "baseName": "wallets",
            "type": "Array<Wallet>"
        },
        {
            "name": "smartContracts",
            "baseName": "smartContracts",
            "type": "Array<SmartContract>"
        }    ];

    static getAttributeTypeMap() {
        return AccountEntity.attributeTypeMap;
    }
}


