/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActivateValidatorsRequestValidatorsInner } from './activateValidatorsRequestValidatorsInner';

/**
* Request to activate validators on the PredepositGuarantee contract. Uses proveWCActivateAndTopUpValidators to handle all validator stages in a single batch call. PREDEPOSITED validators are proven and activated, PROVEN validators are activated, and ACTIVATED validators can be topped up.
*/
export class ActivateValidatorsRequest {
    /**
    * Array of validators to activate.
    */
   'validators': Array<ActivateValidatorsRequestValidatorsInner>;
    /**
    * Optional Ethereum address to simulate the transaction from.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validators",
            "baseName": "validators",
            "type": "Array<ActivateValidatorsRequestValidatorsInner>"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActivateValidatorsRequest.attributeTypeMap;
    }
}


