/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Asset } from './asset';

export class AddLinkedWalletForUserRequest {
   'walletAddress': string;
   'asset': Asset;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "walletAddress",
            "baseName": "walletAddress",
            "type": "string"
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "Asset"
        }    ];

    static getAttributeTypeMap() {
        return AddLinkedWalletForUserRequest.attributeTypeMap;
    }
}

export namespace AddLinkedWalletForUserRequest {
}

