/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ApiKey {
    /**
    * Unique identifier for the API key
    */
   'id': string;
    /**
    * Descriptive name for the API key
    */
   'key_name': string;
    /**
    * The API key value
    */
   'key': string;
    /**
    * The public key associated with the API key
    */
   'pub_key': string;
    /**
    * List of IP addresses or CIDR ranges allowed to use this API key
    */
   'ip_whitelist'?: Array<string>;
    /**
    * Roles associated with the API key
    */
   'roles'?: Array<ApiKey.rolesEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "key_name",
            "baseName": "key_name",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "pub_key",
            "baseName": "pub_key",
            "type": "string"
        },
        {
            "name": "ip_whitelist",
            "baseName": "ip_whitelist",
            "type": "Array<string>"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<ApiKey.rolesEnum>"
        }    ];

    static getAttributeTypeMap() {
        return ApiKey.attributeTypeMap;
    }
}

export namespace ApiKey {
/**
* Roles associated with the API key
*/
export type rolesEnum = 
'admin' | 
'user' | 
'reader';
}

