/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ApiKey {
    /**
    * Unique identifier for the API key
    */
   'id': string;
    /**
    * Descriptive name for the API key
    */
   'keyName': string;
    /**
    * The API key value
    */
   'key': string;
    /**
    * The public key associated with the API key
    */
   'pubKey': string;
    /**
    * List of IP addresses or CIDR ranges allowed to use this API key
    */
   'ipWhitelist'?: Array<string>;
    /**
    * Roles associated with the API key
    */
   'roles'?: Array<ApiKey.rolesEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "keyName",
            "baseName": "keyName",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "pubKey",
            "baseName": "pubKey",
            "type": "string"
        },
        {
            "name": "ipWhitelist",
            "baseName": "ipWhitelist",
            "type": "Array<string>"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<ApiKey.rolesEnum>"
        }    ];

    static getAttributeTypeMap() {
        return ApiKey.attributeTypeMap;
    }
}

export namespace ApiKey {
/**
* Roles associated with the API key
*/
export type rolesEnum = 
'admin' | 
'user' | 
'reader';
}

