/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BurnWstETH {
    /**
    * Amount of wstETH to burn, as a bigint string. Pass the literal \"max\" to burn the full minted liability (computed server-side).
    */
   'amountOfWstETH': string;
    /**
    * Depositor address whose minted balance bounds the \"max\" amount on StvStETH pools (per-depositor). When amountOfWstETH is \"max\" on a pool, provide either fromAddress or simulateAddress; they must be the same if both are given. Ignored for dedicated/STV vaults.
    */
   'fromAddress'?: string;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountOfWstETH",
            "baseName": "amountOfWstETH",
            "type": "string"
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BurnWstETH.attributeTypeMap;
    }
}


