/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ConsolidateValidators {
    /**
    * Array of source validator public keys (hex strings starting with 0x) to consolidate from.
    */
   'sourcePubKeys': Array<string>;
    /**
    * Array of target validator public keys (hex strings starting with 0x) to consolidate to. Must be same length as sourcePubKeys.
    */
   'targetPubKeys': Array<string>;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sourcePubKeys",
            "baseName": "sourcePubKeys",
            "type": "Array<string>"
        },
        {
            "name": "targetPubKeys",
            "baseName": "targetPubKeys",
            "type": "Array<string>"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConsolidateValidators.attributeTypeMap;
    }
}


