/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PartialTransaction } from './partialTransaction';

export class ConsolidateValidatorsResponse {
    /**
    * Array of partial transactions, each representing a consolidation request ready to be signed and submitted
    */
   'transactions'?: Array<PartialTransaction>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<PartialTransaction>"
        }    ];

    static getAttributeTypeMap() {
        return ConsolidateValidatorsResponse.attributeTypeMap;
    }
}


