/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Configuration for timelock controller deployment
*/
export class CreateSTVPoolRequestTimelockConfig {
    /**
    * Minimum delay in seconds before executing queued operations. Passed as a bigint string.
    */
   'minDelaySeconds': string;
    /**
    * Address authorized to propose operations
    */
   'proposer': string;
    /**
    * Address authorized to execute operations
    */
   'executor': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minDelaySeconds",
            "baseName": "minDelaySeconds",
            "type": "string"
        },
        {
            "name": "proposer",
            "baseName": "proposer",
            "type": "string"
        },
        {
            "name": "executor",
            "baseName": "executor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSTVPoolRequestTimelockConfig.attributeTypeMap;
    }
}


