/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateSTVPoolFinishRequestCommonPoolConfig } from './createSTVPoolFinishRequestCommonPoolConfig';
import { CreateSTVPoolFinishRequestIntermediate } from './createSTVPoolFinishRequestIntermediate';
import { CreateSTVPoolFinishRequestTimelockConfig } from './createSTVPoolFinishRequestTimelockConfig';
import { CreateSTVPoolFinishRequestVaultConfig } from './createSTVPoolFinishRequestVaultConfig';

/**
* Parameters for finalizing an STV pool deployment on Lido v3. All config parameters must match those used in createSTVPoolStart.
*/
export class CreateSTVPoolFinishRequest {
   'vaultConfig': CreateSTVPoolFinishRequestVaultConfig;
   'commonPoolConfig': CreateSTVPoolFinishRequestCommonPoolConfig;
   'timelockConfig': CreateSTVPoolFinishRequestTimelockConfig;
    /**
    * Whether the pool requires an allowlist for deposits (must match createSTVPoolStart)
    */
   'allowlistEnabled': boolean;
    /**
    * Address to be granted the ALLOW_LIST_MANAGER_ROLE (must match createSTVPoolStart)
    */
   'allowlistManager': string;
    /**
    * Type of pool (must match createSTVPoolStart). \"stv\" for basic STV pool, \"stvSteth\" for STV stETH pool.
    */
   'poolType': CreateSTVPoolFinishRequest.poolTypeEnum;
    /**
    * Maximum allowed reserve ratio gap in basis points (must match createSTVPoolStart). Required when poolType is \"stvSteth\".
    */
   'reserveRatioGapBP'?: string;
   'intermediate': CreateSTVPoolFinishRequestIntermediate;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vaultConfig",
            "baseName": "vaultConfig",
            "type": "CreateSTVPoolFinishRequestVaultConfig"
        },
        {
            "name": "commonPoolConfig",
            "baseName": "commonPoolConfig",
            "type": "CreateSTVPoolFinishRequestCommonPoolConfig"
        },
        {
            "name": "timelockConfig",
            "baseName": "timelockConfig",
            "type": "CreateSTVPoolFinishRequestTimelockConfig"
        },
        {
            "name": "allowlistEnabled",
            "baseName": "allowlistEnabled",
            "type": "boolean"
        },
        {
            "name": "allowlistManager",
            "baseName": "allowlistManager",
            "type": "string"
        },
        {
            "name": "poolType",
            "baseName": "poolType",
            "type": "CreateSTVPoolFinishRequest.poolTypeEnum"
        },
        {
            "name": "reserveRatioGapBP",
            "baseName": "reserveRatioGapBP",
            "type": "string"
        },
        {
            "name": "intermediate",
            "baseName": "intermediate",
            "type": "CreateSTVPoolFinishRequestIntermediate"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSTVPoolFinishRequest.attributeTypeMap;
    }
}

export namespace CreateSTVPoolFinishRequest {
/**
* Type of pool (must match createSTVPoolStart). \"stv\" for basic STV pool, \"stvSteth\" for STV stETH pool.
*/
export type poolTypeEnum = 
'stv' | 
'stvSteth';
}

