/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateSTVPoolRequestCommonPoolConfig } from './createSTVPoolRequestCommonPoolConfig';
import { CreateSTVPoolRequestTimelockConfig } from './createSTVPoolRequestTimelockConfig';
import { CreateSTVPoolRequestVaultConfig } from './createSTVPoolRequestVaultConfig';

/**
* Parameters for creating a new STV pool on Lido v3
*/
export class CreateSTVPoolRequest {
   'vaultConfig': CreateSTVPoolRequestVaultConfig;
   'commonPoolConfig': CreateSTVPoolRequestCommonPoolConfig;
   'timelockConfig': CreateSTVPoolRequestTimelockConfig;
    /**
    * Whether the pool requires an allowlist for deposits
    */
   'allowlistEnabled': boolean;
    /**
    * Address to be granted the ALLOW_LIST_MANAGER_ROLE. Required when allowlistEnabled is true.
    */
   'allowlistManager': string;
    /**
    * Type of pool to create. \"stv\" for basic STV pool, \"stvSteth\" for STV stETH pool with minting capabilities.
    */
   'poolType': CreateSTVPoolRequest.poolTypeEnum;
    /**
    * Maximum allowed reserve ratio gap in basis points. Required when poolType is \"stvSteth\". Passed as a bigint string.
    */
   'reserveRatioGapBP'?: string;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vaultConfig",
            "baseName": "vaultConfig",
            "type": "CreateSTVPoolRequestVaultConfig"
        },
        {
            "name": "commonPoolConfig",
            "baseName": "commonPoolConfig",
            "type": "CreateSTVPoolRequestCommonPoolConfig"
        },
        {
            "name": "timelockConfig",
            "baseName": "timelockConfig",
            "type": "CreateSTVPoolRequestTimelockConfig"
        },
        {
            "name": "allowlistEnabled",
            "baseName": "allowlistEnabled",
            "type": "boolean"
        },
        {
            "name": "allowlistManager",
            "baseName": "allowlistManager",
            "type": "string"
        },
        {
            "name": "poolType",
            "baseName": "poolType",
            "type": "CreateSTVPoolRequest.poolTypeEnum"
        },
        {
            "name": "reserveRatioGapBP",
            "baseName": "reserveRatioGapBP",
            "type": "string"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSTVPoolRequest.attributeTypeMap;
    }
}

export namespace CreateSTVPoolRequest {
/**
* Type of pool to create. \"stv\" for basic STV pool, \"stvSteth\" for STV stETH pool with minting capabilities.
*/
export type poolTypeEnum = 
'stv' | 
'stvSteth';
}

