/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Deployment state returned by createSTVPoolStart
*/
export class CreateSTVPoolFinishRequestIntermediate {
    /**
    * Dashboard contract address
    */
   'dashboard': string;
    /**
    * Pool proxy contract address
    */
   'poolProxy': string;
    /**
    * Pool implementation contract address
    */
   'poolImpl': string;
    /**
    * Withdrawal queue proxy contract address
    */
   'withdrawalQueueProxy': string;
    /**
    * Withdrawal queue implementation contract address
    */
   'wqImpl': string;
    /**
    * Timelock controller contract address
    */
   'timelock': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dashboard",
            "baseName": "dashboard",
            "type": "string"
        },
        {
            "name": "poolProxy",
            "baseName": "poolProxy",
            "type": "string"
        },
        {
            "name": "poolImpl",
            "baseName": "poolImpl",
            "type": "string"
        },
        {
            "name": "withdrawalQueueProxy",
            "baseName": "withdrawalQueueProxy",
            "type": "string"
        },
        {
            "name": "wqImpl",
            "baseName": "wqImpl",
            "type": "string"
        },
        {
            "name": "timelock",
            "baseName": "timelock",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSTVPoolFinishRequestIntermediate.attributeTypeMap;
    }
}


