/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Summary statistics for daily rewards
*/
export class DailyRewardSummaryStats {
    /**
    * Average rewards per validator in ETH
    */
   'average_rewards_per_validator_eth': string;
    /**
    * Median rewards per validator in ETH
    */
   'median_rewards_per_validator_eth': string;
    /**
    * Maximum rewards earned by any validator in ETH
    */
   'max_rewards_per_validator_eth': string;
    /**
    * Minimum rewards earned by any validator in ETH
    */
   'min_rewards_per_validator_eth': string;
    /**
    * Total number of blocks proposed on this date
    */
   'total_blocks_proposed': number;
    /**
    * Average attestation efficiency across all validators
    */
   'average_attestation_efficiency': number;
    /**
    * Number of validators that received MEV rewards on this date
    */
   'validators_with_mev': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "average_rewards_per_validator_eth",
            "baseName": "average_rewards_per_validator_eth",
            "type": "string"
        },
        {
            "name": "median_rewards_per_validator_eth",
            "baseName": "median_rewards_per_validator_eth",
            "type": "string"
        },
        {
            "name": "max_rewards_per_validator_eth",
            "baseName": "max_rewards_per_validator_eth",
            "type": "string"
        },
        {
            "name": "min_rewards_per_validator_eth",
            "baseName": "min_rewards_per_validator_eth",
            "type": "string"
        },
        {
            "name": "total_blocks_proposed",
            "baseName": "total_blocks_proposed",
            "type": "number"
        },
        {
            "name": "average_attestation_efficiency",
            "baseName": "average_attestation_efficiency",
            "type": "number"
        },
        {
            "name": "validators_with_mev",
            "baseName": "validators_with_mev",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DailyRewardSummaryStats.attributeTypeMap;
    }
}


