/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class DepositAndMintWsteth {
    /**
    * Amount of ETH to deposit, as a bigint string in wei.
    */
   'amount': string;
    /**
    * Optional referral address. Defaults to zero address if not provided.
    */
   'referral'?: string;
    /**
    * Optional amount of wstETH to mint against the deposit, as a bigint string. Pass \"0\" or omit to deposit without minting.
    */
   'wstethToMint'?: string;
    /**
    * Optional Ethereum address to simulate the transaction from.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "referral",
            "baseName": "referral",
            "type": "string"
        },
        {
            "name": "wstethToMint",
            "baseName": "wstethToMint",
            "type": "string"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DepositAndMintWsteth.attributeTypeMap;
    }
}


