/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DepositAddress } from './depositAddress';

export class DepositAddressesForUserResponse {
   'userId': string;
   'depositAccounts': Array<DepositAddress>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "depositAccounts",
            "baseName": "depositAccounts",
            "type": "Array<DepositAddress>"
        }    ];

    static getAttributeTypeMap() {
        return DepositAddressesForUserResponse.attributeTypeMap;
    }
}


