/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EthereumValidatorKeyKeystore } from './ethereumValidatorKeyKeystore';

/**
* Ethereum pregenerated validator key, used for staking operations on the blockchain.
*/
export class EthereumValidatorKey {
   'keystore': EthereumValidatorKeyKeystore;
   'password': string;
   'enable': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keystore",
            "baseName": "keystore",
            "type": "EthereumValidatorKeyKeystore"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "enable",
            "baseName": "enable",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EthereumValidatorKey.attributeTypeMap;
    }
}


