/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class EthereumValidatorKeyKeystoreCryptoCipherParams {
   'iv': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "iv",
            "baseName": "iv",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EthereumValidatorKeyKeystoreCryptoCipherParams.attributeTypeMap;
    }
}


