/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class FundVault {
    /**
    * Amount of Eth denominated in wei
    */
   'amount': string;
    /**
    * Ethereum address that receives minted pool shares (STV tokens). Only applicable to pool vaults (STV, STV_STETH). If not provided, defaults to the authenticated user\'s address. Ignored for dedicated vaults.
    */
   'sharesRecipient'?: string;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "sharesRecipient",
            "baseName": "sharesRecipient",
            "type": "string"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FundVault.attributeTypeMap;
    }
}


