/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GenerateApiKeyRequest {
    /**
    * A descriptive name for the API key.
    */
   'keyName': string;
    /**
    * The public part of an RSA private keypair in PEM format.
    */
   'publicKey': string;
   'whitelistedIPs'?: Array<string>;
    /**
    * The rights associated with the API key.
    */
   'keyRights'?: Array<GenerateApiKeyRequest.keyRightsEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keyName",
            "baseName": "keyName",
            "type": "string"
        },
        {
            "name": "publicKey",
            "baseName": "publicKey",
            "type": "string"
        },
        {
            "name": "whitelistedIPs",
            "baseName": "whitelistedIPs",
            "type": "Array<string>"
        },
        {
            "name": "keyRights",
            "baseName": "keyRights",
            "type": "Array<GenerateApiKeyRequest.keyRightsEnum>"
        }    ];

    static getAttributeTypeMap() {
        return GenerateApiKeyRequest.attributeTypeMap;
    }
}

export namespace GenerateApiKeyRequest {
/**
* The rights associated with the API key.
*/
export type keyRightsEnum = 
'user' | 
'reader';
}

