/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetLazyOracleReportCallData200ResponseDestructuredCalldata {
   '_vault'?: string;
   '_totalValue'?: string;
   '_cumulativeLidoFees'?: string;
   '_liabilityShares'?: string;
   '_maxLiabilityShares'?: string;
   '_slashingReserve'?: string;
   '_proof'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_vault",
            "baseName": "_vault",
            "type": "string"
        },
        {
            "name": "_totalValue",
            "baseName": "_totalValue",
            "type": "string"
        },
        {
            "name": "_cumulativeLidoFees",
            "baseName": "_cumulativeLidoFees",
            "type": "string"
        },
        {
            "name": "_liabilityShares",
            "baseName": "_liabilityShares",
            "type": "string"
        },
        {
            "name": "_maxLiabilityShares",
            "baseName": "_maxLiabilityShares",
            "type": "string"
        },
        {
            "name": "_slashingReserve",
            "baseName": "_slashingReserve",
            "type": "string"
        },
        {
            "name": "_proof",
            "baseName": "_proof",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return GetLazyOracleReportCallData200ResponseDestructuredCalldata.attributeTypeMap;
    }
}


