/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetMarketplaceMetadata200Response {
    /**
    * Total number of RFQs in the marketplace
    */
   'totalRFQs'?: number;
    /**
    * Number of active RFQs
    */
   'activeRFQs'?: number;
    /**
    * Number of expired RFQs
    */
   'expiredRFQs'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalRFQs",
            "baseName": "totalRFQs",
            "type": "number"
        },
        {
            "name": "activeRFQs",
            "baseName": "activeRFQs",
            "type": "number"
        },
        {
            "name": "expiredRFQs",
            "baseName": "expiredRFQs",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetMarketplaceMetadata200Response.attributeTypeMap;
    }
}


