/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetOperatorGroup200Response {
    /**
    * The operator address
    */
   'operator': string;
    /**
    * The share limit for the operator group
    */
   'shareLimit': string;
    /**
    * The liability shares for the operator group
    */
   'liabilityShares': string;
    /**
    * The tier IDs associated with the operator group
    */
   'tierIds': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string"
        },
        {
            "name": "shareLimit",
            "baseName": "shareLimit",
            "type": "string"
        },
        {
            "name": "liabilityShares",
            "baseName": "liabilityShares",
            "type": "string"
        },
        {
            "name": "tierIds",
            "baseName": "tierIds",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return GetOperatorGroup200Response.attributeTypeMap;
    }
}


