/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPoolStats200ResponsePool } from './getPoolStats200ResponsePool';
import { GetPoolStats200ResponseStethPoolStats } from './getPoolStats200ResponseStethPoolStats';

export class GetPoolStats200Response {
   'pool': GetPoolStats200ResponsePool;
   'totalSupply': string;
   'totalAssets': string;
   'depositsPaused': boolean;
   'currentStvRate': string;
   'currentStethShareRate': string;
   'stethPoolStats': GetPoolStats200ResponseStethPoolStats | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pool",
            "baseName": "pool",
            "type": "GetPoolStats200ResponsePool"
        },
        {
            "name": "totalSupply",
            "baseName": "totalSupply",
            "type": "string"
        },
        {
            "name": "totalAssets",
            "baseName": "totalAssets",
            "type": "string"
        },
        {
            "name": "depositsPaused",
            "baseName": "depositsPaused",
            "type": "boolean"
        },
        {
            "name": "currentStvRate",
            "baseName": "currentStvRate",
            "type": "string"
        },
        {
            "name": "currentStethShareRate",
            "baseName": "currentStethShareRate",
            "type": "string"
        },
        {
            "name": "stethPoolStats",
            "baseName": "stethPoolStats",
            "type": "GetPoolStats200ResponseStethPoolStats"
        }    ];

    static getAttributeTypeMap() {
        return GetPoolStats200Response.attributeTypeMap;
    }
}


