/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPoolParticipants200ResponseParticipantsInner } from './getPoolParticipants200ResponseParticipantsInner';
import { GetPoolParticipants200ResponsePool } from './getPoolParticipants200ResponsePool';

export class GetPoolParticipants200Response {
   'pool': GetPoolParticipants200ResponsePool;
   'participants': Array<GetPoolParticipants200ResponseParticipantsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pool",
            "baseName": "pool",
            "type": "GetPoolParticipants200ResponsePool"
        },
        {
            "name": "participants",
            "baseName": "participants",
            "type": "Array<GetPoolParticipants200ResponseParticipantsInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetPoolParticipants200Response.attributeTypeMap;
    }
}


