/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPoolUserStats200ResponsePool } from './getPoolUserStats200ResponsePool';
import { GetPoolUserStats200ResponseStethUserStats } from './getPoolUserStats200ResponseStethUserStats';

export class GetPoolUserStats200Response {
   'pool': GetPoolUserStats200ResponsePool;
   'userAddress': string;
   'balanceOf': string;
   'assetsOf': string;
   'stethUserStats': GetPoolUserStats200ResponseStethUserStats | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pool",
            "baseName": "pool",
            "type": "GetPoolUserStats200ResponsePool"
        },
        {
            "name": "userAddress",
            "baseName": "userAddress",
            "type": "string"
        },
        {
            "name": "balanceOf",
            "baseName": "balanceOf",
            "type": "string"
        },
        {
            "name": "assetsOf",
            "baseName": "assetsOf",
            "type": "string"
        },
        {
            "name": "stethUserStats",
            "baseName": "stethUserStats",
            "type": "GetPoolUserStats200ResponseStethUserStats"
        }    ];

    static getAttributeTypeMap() {
        return GetPoolUserStats200Response.attributeTypeMap;
    }
}


