/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPoolPreview200ResponsePool } from './getPoolPreview200ResponsePool';

export class GetPoolPreview200Response {
   'pool': GetPoolPreview200ResponsePool;
   'previewDeposit': string | null;
   'previewWithdraw': string | null;
   'previewRedeem': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pool",
            "baseName": "pool",
            "type": "GetPoolPreview200ResponsePool"
        },
        {
            "name": "previewDeposit",
            "baseName": "previewDeposit",
            "type": "string"
        },
        {
            "name": "previewWithdraw",
            "baseName": "previewWithdraw",
            "type": "string"
        },
        {
            "name": "previewRedeem",
            "baseName": "previewRedeem",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetPoolPreview200Response.attributeTypeMap;
    }
}


