/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetQuarantineInfo200Response {
   'isActive': string;
   'pendingTotalValueIncrease': string;
   'startTimestamp': string;
   'endTimestamp': string;
   'totalValueRemainder'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "string"
        },
        {
            "name": "pendingTotalValueIncrease",
            "baseName": "pendingTotalValueIncrease",
            "type": "string"
        },
        {
            "name": "startTimestamp",
            "baseName": "startTimestamp",
            "type": "string"
        },
        {
            "name": "endTimestamp",
            "baseName": "endTimestamp",
            "type": "string"
        },
        {
            "name": "totalValueRemainder",
            "baseName": "totalValueRemainder",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetQuarantineInfo200Response.attributeTypeMap;
    }
}


