/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MinedBlock } from './minedBlock';

export class GetSmartContractMinedBlocks200Response {
   'blocks': Array<MinedBlock>;
    /**
    * Total number of mined blocks
    */
   'total': number;
    /**
    * Total number of pages
    */
   'pages': number;
    /**
    * Current page number
    */
   'currentPage': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "Array<MinedBlock>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "pages",
            "baseName": "pages",
            "type": "number"
        },
        {
            "name": "currentPage",
            "baseName": "currentPage",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetSmartContractMinedBlocks200Response.attributeTypeMap;
    }
}


