/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPoolPreview200ResponsePool } from './getPoolPreview200ResponsePool';

export class GetTimelockDelay200Response {
   'timelock': GetPoolPreview200ResponsePool;
   'minDelay': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timelock",
            "baseName": "timelock",
            "type": "GetPoolPreview200ResponsePool"
        },
        {
            "name": "minDelay",
            "baseName": "minDelay",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetTimelockDelay200Response.attributeTypeMap;
    }
}


