/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidatorWithdrawal } from './validatorWithdrawal';

export class GetWithdrawalsResponse {
   'withdrawals': Array<ValidatorWithdrawal>;
    /**
    * Total number of pages
    */
   'pages': number;
    /**
    * Total number of withdrawals
    */
   'total': number;
    /**
    * Current page number
    */
   'currentPage': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "withdrawals",
            "baseName": "withdrawals",
            "type": "Array<ValidatorWithdrawal>"
        },
        {
            "name": "pages",
            "baseName": "pages",
            "type": "number"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "currentPage",
            "baseName": "currentPage",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetWithdrawalsResponse.attributeTypeMap;
    }
}


