/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetWithdrawalQueueUserStats200ResponseRequestsInner {
   'requestId': string;
   'amountOfStv': string;
   'amountOfStethShares': string;
   'amountOfAssets': string;
   'owner': string;
   'timestamp': string;
   'isFinalized': boolean;
   'isClaimed': boolean;
   'claimableEther': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string"
        },
        {
            "name": "amountOfStv",
            "baseName": "amountOfStv",
            "type": "string"
        },
        {
            "name": "amountOfStethShares",
            "baseName": "amountOfStethShares",
            "type": "string"
        },
        {
            "name": "amountOfAssets",
            "baseName": "amountOfAssets",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "isFinalized",
            "baseName": "isFinalized",
            "type": "boolean"
        },
        {
            "name": "isClaimed",
            "baseName": "isClaimed",
            "type": "boolean"
        },
        {
            "name": "claimableEther",
            "baseName": "claimableEther",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetWithdrawalQueueUserStats200ResponseRequestsInner.attributeTypeMap;
    }
}


