/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPoolPreview200ResponsePool } from './getPoolPreview200ResponsePool';
import { GetWithdrawalRequests200ResponseRequestsInner } from './getWithdrawalRequests200ResponseRequestsInner';

export class GetWithdrawalRequests200Response {
   'withdrawalQueue': GetPoolPreview200ResponsePool;
   'requests': Array<GetWithdrawalRequests200ResponseRequestsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "withdrawalQueue",
            "baseName": "withdrawalQueue",
            "type": "GetPoolPreview200ResponsePool"
        },
        {
            "name": "requests",
            "baseName": "requests",
            "type": "Array<GetWithdrawalRequests200ResponseRequestsInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetWithdrawalRequests200Response.attributeTypeMap;
    }
}


