/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LidoContractsDashboard } from './lidoContractsDashboard';
import { LidoContractsStakingVault } from './lidoContractsStakingVault';
import { ValidatorProvider } from './validatorProvider';

/**
* Lido contract addresses for a staking setup
*/
export class LidoContracts {
    /**
    * Name of the staking contract set
    */
   'name'?: string;
   'stakingVault': LidoContractsStakingVault;
   'dashboard': LidoContractsDashboard;
   'validator_provider': ValidatorProvider;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "stakingVault",
            "baseName": "stakingVault",
            "type": "LidoContractsStakingVault"
        },
        {
            "name": "dashboard",
            "baseName": "dashboard",
            "type": "LidoContractsDashboard"
        },
        {
            "name": "validator_provider",
            "baseName": "validator_provider",
            "type": "ValidatorProvider"
        }    ];

    static getAttributeTypeMap() {
        return LidoContracts.attributeTypeMap;
    }
}

export namespace LidoContracts {
}

