/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class LidoStakingContractsWithDataVaultData {
    /**
    * Total liability of the vault in wei
    */
   'totalValue'?: string;
    /**
    * Total assets of the vault in wei
    */
   'ethBalance'?: string;
    /**
    * Total staked amount in wei
    */
   'stake'?: string;
    /**
    * Total shares issued by the vault
    */
   'liabilityShares'?: string;
    /**
    * Total stETH liability in wei
    */
   'liabilityStETH'?: string;
    /**
    * Total locked ETH in wei
    */
   'lockedETH'?: string;
    /**
    * Total withdrawable ETH in wei
    */
   'withdrawableValue'?: string;
    /**
    * Remaining capacity to mint shares in wei
    */
   'remainingMintingCapacityShares'?: string;
    /**
    * Remaining capacity to mint shares in stETH
    */
   'remainingMintingCapacityStETH'?: string;
    /**
    * Total capacity to mint shares in wei
    */
   'totalMintingCapacityShares'?: string;
    /**
    * Total capacity to mint stETH
    */
   'totalMintingCapacityStETH'?: string;
    /**
    * Accrued fee in wei
    */
   'accruedFee'?: string;
    /**
    * Vault owner address
    */
   'owner'?: string;
    /**
    * Maximum number of stETH shares that can be minted (in wei)
    */
   'shareLimit'?: string;
    /**
    * Index of the vault in the list of vaults
    */
   'vaultIndex'?: number;
    /**
    * Vault hub connection status. `connected` = fully connected; `disconnecting` = voluntary disconnect initiated, transition period (same restrictions as disconnected); `disconnected` = not connected. When not `connected`, only voluntary disconnect, withdrawal, and connect to vault hub are allowed. 
    */
   'vaultHubConnectionStatus'?: LidoStakingContractsWithDataVaultData.vaultHubConnectionStatusEnum;
    /**
    * Share of ether locked as additional reserve (in basis points)
    */
   'reserveRatioBP'?: string;
    /**
    * Threshold for forced rebalance (in basis points, e.g., 4950 = 49.5%). Critical for health factor calculation.
    */
   'forcedRebalanceThresholdBP'?: string;
    /**
    * Infrastructure fee in basis points
    */
   'infraFeeBP'?: string;
    /**
    * Liquidity fee in basis points
    */
   'liquidityFeeBP'?: string;
    /**
    * Reservation fee in basis points
    */
   'reservationFeeBP'?: string;
    /**
    * Node operator fee in basis points (1 BP = 0.01%). The share of staking rewards taken by the node operator.
    */
   'nodeOperatorFeeBP'?: string;
    /**
    * If true, vault owner intends to pause beacon chain deposits
    */
   'beaconChainDepositsPauseIntent'?: boolean;
    /**
    * Tier ID on the operator grid
    */
   'tierId'?: string;
    /**
    * Node operator address. A value of 0xffffffffffffffffffffffffffffffffffffffff indicates that the operator is not registered on the operator grid
    */
   'nodeOperator'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalValue",
            "baseName": "totalValue",
            "type": "string"
        },
        {
            "name": "ethBalance",
            "baseName": "ethBalance",
            "type": "string"
        },
        {
            "name": "stake",
            "baseName": "stake",
            "type": "string"
        },
        {
            "name": "liabilityShares",
            "baseName": "liabilityShares",
            "type": "string"
        },
        {
            "name": "liabilityStETH",
            "baseName": "liabilityStETH",
            "type": "string"
        },
        {
            "name": "lockedETH",
            "baseName": "lockedETH",
            "type": "string"
        },
        {
            "name": "withdrawableValue",
            "baseName": "withdrawableValue",
            "type": "string"
        },
        {
            "name": "remainingMintingCapacityShares",
            "baseName": "remainingMintingCapacityShares",
            "type": "string"
        },
        {
            "name": "remainingMintingCapacityStETH",
            "baseName": "remainingMintingCapacityStETH",
            "type": "string"
        },
        {
            "name": "totalMintingCapacityShares",
            "baseName": "totalMintingCapacityShares",
            "type": "string"
        },
        {
            "name": "totalMintingCapacityStETH",
            "baseName": "totalMintingCapacityStETH",
            "type": "string"
        },
        {
            "name": "accruedFee",
            "baseName": "accruedFee",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "shareLimit",
            "baseName": "shareLimit",
            "type": "string"
        },
        {
            "name": "vaultIndex",
            "baseName": "vaultIndex",
            "type": "number"
        },
        {
            "name": "vaultHubConnectionStatus",
            "baseName": "vaultHubConnectionStatus",
            "type": "LidoStakingContractsWithDataVaultData.vaultHubConnectionStatusEnum"
        },
        {
            "name": "reserveRatioBP",
            "baseName": "reserveRatioBP",
            "type": "string"
        },
        {
            "name": "forcedRebalanceThresholdBP",
            "baseName": "forcedRebalanceThresholdBP",
            "type": "string"
        },
        {
            "name": "infraFeeBP",
            "baseName": "infraFeeBP",
            "type": "string"
        },
        {
            "name": "liquidityFeeBP",
            "baseName": "liquidityFeeBP",
            "type": "string"
        },
        {
            "name": "reservationFeeBP",
            "baseName": "reservationFeeBP",
            "type": "string"
        },
        {
            "name": "nodeOperatorFeeBP",
            "baseName": "nodeOperatorFeeBP",
            "type": "string"
        },
        {
            "name": "beaconChainDepositsPauseIntent",
            "baseName": "beaconChainDepositsPauseIntent",
            "type": "boolean"
        },
        {
            "name": "tierId",
            "baseName": "tierId",
            "type": "string"
        },
        {
            "name": "nodeOperator",
            "baseName": "nodeOperator",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LidoStakingContractsWithDataVaultData.attributeTypeMap;
    }
}

export namespace LidoStakingContractsWithDataVaultData {
/**
* Vault hub connection status. `connected` = fully connected; `disconnecting` = voluntary disconnect initiated, transition period (same restrictions as disconnected); `disconnected` = not connected. When not `connected`, only voluntary disconnect, withdrawal, and connect to vault hub are allowed. 
*/
export type vaultHubConnectionStatusEnum = 
'connected' | 
'disconnected' | 
'disconnecting';
}

