/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Outstanding Lido obligations for the vault, read from the dashboard. Reflects the latest oracle report.
*/
export class LidoStakingContractsWithDataVaultDataObligations {
    /**
    * Amount of shares to burn or rebalance to clear redemption obligations (wei bigint string).
    */
   'sharesToBurn': string;
    /**
    * Amount of unsettled Lido fees owed to the treasury (wei bigint string).
    */
   'feesToSettle': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sharesToBurn",
            "baseName": "sharesToBurn",
            "type": "string"
        },
        {
            "name": "feesToSettle",
            "baseName": "feesToSettle",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LidoStakingContractsWithDataVaultDataObligations.attributeTypeMap;
    }
}


