/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class LidoStakingContractsWithDataAprHistoryInner {
    /**
    * Gross staking APR in percent, before any fees are subtracted.
    */
   'grossAPR': number;
    /**
    * Net staking APR in percent, after node operator fee and Lido protocol fee. Null when stETH price history is unavailable for the reporting period.
    */
   'netAPR': number | null;
    /**
    * Carry spread APR in percent — the yield delta versus the stETH benchmark. Calculated as (bottomLine × 100 × 31536000) / (previousTVL × periodSeconds). Null when stETH price history is unavailable for the reporting period. 
    */
   'carrySpreadAPR': number | null;
    /**
    * Gross staking rewards for the period in wei. Calculated as (totalValueCurr − totalValuePrev) − (inOutDeltaCurr − inOutDeltaPrev). 
    */
   'grossStakingRewardsWei': string;
    /**
    * Net staking rewards for the period in wei, after nodeOperatorFeeWei and lidoProtocolFeeWei. Null when netAPR is null.
    */
   'netStakingRewardsWei': string | null;
    /**
    * Bottom line for the period in wei — net staking rewards minus the stETH liability rebase cost. Null when carrySpreadAPR is null. 
    */
   'bottomLineWei': string | null;
    /**
    * Cost of the stETH liability rebase for the period in wei. Calculated as liabilitySharesPrev × (stETHPriceCurr − stETHPricePrev) / 1e18. Null when carrySpreadAPR is null. 
    */
   'stEthLiabilityRebaseCostWei': string | null;
    /**
    * Node operator (infrastructure) fee charged for the period in wei. Null when netAPR is null.
    */
   'nodeOperatorFeeWei': string | null;
    /**
    * Lido protocol fee charged for the period in wei (change in cumulative Lido fees).
    */
   'lidoProtocolFeeWei': string;
    /**
    * Total vault value at the start of the period in wei. Used as the APR denominator.
    */
   'previousTVLWei': string;
    /**
    * Duration of the measurement period in seconds (current report timestamp − previous report timestamp).
    */
   'periodSeconds': number;
    /**
    * Unix timestamp of the current oracle report.
    */
   'reportTimestamp': number;
    /**
    * Unix timestamp of the previous oracle report.
    */
   'prevReportTimestamp': number;
    /**
    * IPFS CID of the current (newer) oracle report used in this APR calculation.
    */
   'currentReportCID': string;
    /**
    * IPFS CID of the previous (older) oracle report used in this APR calculation.
    */
   'prevReportCID': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "grossAPR",
            "baseName": "grossAPR",
            "type": "number"
        },
        {
            "name": "netAPR",
            "baseName": "netAPR",
            "type": "number"
        },
        {
            "name": "carrySpreadAPR",
            "baseName": "carrySpreadAPR",
            "type": "number"
        },
        {
            "name": "grossStakingRewardsWei",
            "baseName": "grossStakingRewardsWei",
            "type": "string"
        },
        {
            "name": "netStakingRewardsWei",
            "baseName": "netStakingRewardsWei",
            "type": "string"
        },
        {
            "name": "bottomLineWei",
            "baseName": "bottomLineWei",
            "type": "string"
        },
        {
            "name": "stEthLiabilityRebaseCostWei",
            "baseName": "stEthLiabilityRebaseCostWei",
            "type": "string"
        },
        {
            "name": "nodeOperatorFeeWei",
            "baseName": "nodeOperatorFeeWei",
            "type": "string"
        },
        {
            "name": "lidoProtocolFeeWei",
            "baseName": "lidoProtocolFeeWei",
            "type": "string"
        },
        {
            "name": "previousTVLWei",
            "baseName": "previousTVLWei",
            "type": "string"
        },
        {
            "name": "periodSeconds",
            "baseName": "periodSeconds",
            "type": "number"
        },
        {
            "name": "reportTimestamp",
            "baseName": "reportTimestamp",
            "type": "number"
        },
        {
            "name": "prevReportTimestamp",
            "baseName": "prevReportTimestamp",
            "type": "number"
        },
        {
            "name": "currentReportCID",
            "baseName": "currentReportCID",
            "type": "string"
        },
        {
            "name": "prevReportCID",
            "baseName": "prevReportCID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LidoStakingContractsWithDataAprHistoryInner.attributeTypeMap;
    }
}


