/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Pool contract details (only present for STV pool and STV stETH pool vaults)
*/
export class LidoContractsPool {
   'address': string;
   'type': LidoContractsPool.typeEnum;
    /**
    * ERC20 token name of the pool
    */
   'name'?: string;
    /**
    * ERC20 token symbol of the pool
    */
   'symbol'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "LidoContractsPool.typeEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LidoContractsPool.attributeTypeMap;
    }
}

export namespace LidoContractsPool {
/**
* 
*/
export type typeEnum = 
'stv' | 
'stvSteth';
}

