/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class MintStETH {
    /**
    * Address of the recipient of the stETH tokens. Required for dedicated/STV vaults, must not be provided for StvStETH pools.
    */
   'recipient'?: string;
    /**
    * Amount of STETH (18 decimals) to mint, as a bigint string in wei. Pass the literal \"max\" to mint the full remaining capacity (computed server-side).
    */
   'amountOfStETH': string;
    /**
    * Depositor address whose remaining minting capacity bounds the \"max\" amount on StvStETH pools (per-depositor). When amountOfStETH is \"max\" on a pool, provide either fromAddress or simulateAddress; they must be the same if both are given. Ignored for dedicated/STV vaults.
    */
   'fromAddress'?: string;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "amountOfStETH",
            "baseName": "amountOfStETH",
            "type": "string"
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MintStETH.attributeTypeMap;
    }
}


