/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationEventType } from './notificationEventType';

export class Notification {
   'id': string;
   'azure_id': string;
   'staking_vault_id': string;
   'event_type': NotificationEventType;
   'severity': Notification.severityEnum;
   'title': string;
   'message': string;
   'payload': { [key: string]: any; };
    /**
    * Unix timestamp in milliseconds
    */
   'created_at': number;
    /**
    * Unix timestamp in milliseconds; absent means unread
    */
   'read_at'?: number;
    /**
    * CosmosDB TTL in seconds
    */
   'ttl'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "azure_id",
            "baseName": "azure_id",
            "type": "string"
        },
        {
            "name": "staking_vault_id",
            "baseName": "staking_vault_id",
            "type": "string"
        },
        {
            "name": "event_type",
            "baseName": "event_type",
            "type": "NotificationEventType"
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "Notification.severityEnum"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "number"
        },
        {
            "name": "read_at",
            "baseName": "read_at",
            "type": "number"
        },
        {
            "name": "ttl",
            "baseName": "ttl",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Notification.attributeTypeMap;
    }
}

export namespace Notification {
/**
* 
*/
export type severityEnum = 
'info' | 
'warning' | 
'error';
}

