/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class OrderUpdatePayload {
    /**
    * Unique identifier for the updated order.
    */
   'orderId'?: string;
    /**
    * New status of the order.
    */
   'status'?: string;
    /**
    * Additional details regarding the order update.
    */
   'details'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return OrderUpdatePayload.attributeTypeMap;
    }
}


