/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StakeStepElement } from './stakeStepElement';
import { StepStatus } from './stepStatus';
import { UnstakeStep } from './unstakeStep';
import { UnstakeStepElement } from './unstakeStepElement';
import { WithdrawalStepElement } from './withdrawalStepElement';

export class OrderDocumentSteps {
   'steps'?: Array<UnstakeStep>;
   'status'?: StepStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<UnstakeStep>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StepStatus"
        }    ];

    static getAttributeTypeMap() {
        return OrderDocumentSteps.attributeTypeMap;
    }
}

export namespace OrderDocumentSteps {
}

