/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Represents a member of an organization
*/
export class OrganizationMember {
    /**
    * The Auth0 user ID of the member
    */
   'memberId': string;
    /**
    * The email address of the member
    */
   'email': string;
    /**
    * The display name of the member
    */
   'name'?: string;
    /**
    * The role of the member within the organization
    */
   'role': OrganizationMember.roleEnum;
    /**
    * When the member joined the organization
    */
   'joinedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "memberId",
            "baseName": "memberId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "OrganizationMember.roleEnum"
        },
        {
            "name": "joinedAt",
            "baseName": "joinedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationMember.attributeTypeMap;
    }
}

export namespace OrganizationMember {
/**
* The role of the member within the organization
*/
export type roleEnum = 
'admin' | 
'reader';
}

