/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Partial eth JSON-RPC transaction
*/
export class PartialTransaction {
   'from'?: string;
   'to': string;
   'value'?: string;
   'data': string;
    /**
    * EIP-1559 gas limit estimate (hex).
    */
   'gas': string;
    /**
    * EIP-1559 max fee per gas (hex).
    */
   'maxFeePerGas': string;
    /**
    * EIP-1559 max priority fee per gas / miner tip (hex).
    */
   'maxPriorityFeePerGas': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        },
        {
            "name": "gas",
            "baseName": "gas",
            "type": "string"
        },
        {
            "name": "maxFeePerGas",
            "baseName": "maxFeePerGas",
            "type": "string"
        },
        {
            "name": "maxPriorityFeePerGas",
            "baseName": "maxPriorityFeePerGas",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PartialTransaction.attributeTypeMap;
    }
}


