/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PoolUserStatsHistoryResponseSeriesInner } from './poolUserStatsHistoryResponseSeriesInner';
import { PoolUserStatsHistoryResponseTotals } from './poolUserStatsHistoryResponseTotals';

export class PoolUserStatsHistoryResponse {
   'contractsId': string;
   'userAddress': string;
   'poolType': string;
   'series': Array<PoolUserStatsHistoryResponseSeriesInner>;
   'totals': PoolUserStatsHistoryResponseTotals;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contractsId",
            "baseName": "contractsId",
            "type": "string"
        },
        {
            "name": "userAddress",
            "baseName": "userAddress",
            "type": "string"
        },
        {
            "name": "poolType",
            "baseName": "poolType",
            "type": "string"
        },
        {
            "name": "series",
            "baseName": "series",
            "type": "Array<PoolUserStatsHistoryResponseSeriesInner>"
        },
        {
            "name": "totals",
            "baseName": "totals",
            "type": "PoolUserStatsHistoryResponseTotals"
        }    ];

    static getAttributeTypeMap() {
        return PoolUserStatsHistoryResponse.attributeTypeMap;
    }
}


