/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PoolUserStatsHistoryResponseTotals {
    /**
    * The user\'s ETH balance now — shares held (every indexed share movement applied, including those after the last report) valued at the latest report\'s stv rate, plus withdrawals requested but not yet claimed. Independent of fromTs/toTs/n.
    */
   'currentEthBalanceWei': string;
    /**
    * Unrealized rewards held in the balance now (see currentRewardsWei), with every indexed share movement applied, including those after the last report — 0 once the position has been fully withdrawn. Independent of fromTs/toTs/n. lifetimeRewardsWei − currentEthRewardsWei approximates the portion already realized through withdrawals.
    */
   'currentEthRewardsWei': string;
   'lifetimeRewardsWei': string;
   'lifetimeFeesWei': string;
   'lifetimeLiquidityFeeWei': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentEthBalanceWei",
            "baseName": "currentEthBalanceWei",
            "type": "string"
        },
        {
            "name": "currentEthRewardsWei",
            "baseName": "currentEthRewardsWei",
            "type": "string"
        },
        {
            "name": "lifetimeRewardsWei",
            "baseName": "lifetimeRewardsWei",
            "type": "string"
        },
        {
            "name": "lifetimeFeesWei",
            "baseName": "lifetimeFeesWei",
            "type": "string"
        },
        {
            "name": "lifetimeLiquidityFeeWei",
            "baseName": "lifetimeLiquidityFeeWei",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PoolUserStatsHistoryResponseTotals.attributeTypeMap;
    }
}


