/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PartialTransaction } from './partialTransaction';
import { PredepositRequestDepositsInner } from './predepositRequestDepositsInner';

/**
* Encoded predeposit transaction together with the validator deposit data it submits. When the deposit data was generated server-side (because `deposits` was omitted), the generated `pubkey`, `signature` and `depositDataRoot` for each validator are echoed back here. 
*/
export class PredepositResponse {
   'transaction': PartialTransaction;
    /**
    * The validator deposit data included in the predeposit transaction.
    */
   'deposits': Array<PredepositRequestDepositsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "PartialTransaction"
        },
        {
            "name": "deposits",
            "baseName": "deposits",
            "type": "Array<PredepositRequestDepositsInner>"
        }    ];

    static getAttributeTypeMap() {
        return PredepositResponse.attributeTypeMap;
    }
}


