/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class PredepositRequestDepositsInner {
    /**
    * Validator BLS public key (48 bytes hex).
    */
   'pubkey': string;
    /**
    * BLS signature (96 bytes hex).
    */
   'signature': string;
    /**
    * Deposit data Merkle root (32 bytes hex).
    */
   'depositDataRoot': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pubkey",
            "baseName": "pubkey",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "depositDataRoot",
            "baseName": "depositDataRoot",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PredepositRequestDepositsInner.attributeTypeMap;
    }
}


