/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PredepositRequestDepositsInner } from './predepositRequestDepositsInner';

/**
* Request to encode a predeposit transaction for the PredepositGuarantee contract. Provide either the full `deposits` array, or omit it entirely to have the 1 ETH deposit data generated server-side (only supported for node operators that support generating it for a 1 ETH deposit — currently `northstake` and `myrmidon`). 
*/
export class PredepositRequest {
    /**
    * Array of validator deposit data. Optional — when omitted, deposit data for a single 1 ETH predeposit is generated server-side for supported node operators. 
    */
   'deposits'?: Array<PredepositRequestDepositsInner>;
    /**
    * Optional Ethereum address to simulate the transaction from. If provided, the transaction will be simulated and any revert errors will be returned.
    */
   'simulateAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deposits",
            "baseName": "deposits",
            "type": "Array<PredepositRequestDepositsInner>"
        },
        {
            "name": "simulateAddress",
            "baseName": "simulateAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PredepositRequest.attributeTypeMap;
    }
}


