/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class RFQDocumentUpdate {
   'best_quote': number;
   'liquidity_id': string;
   'seller_status': string;
   'liquidity_settlement_hash': string;
   'sp_withdrawal_tx_hash'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "best_quote",
            "baseName": "best_quote",
            "type": "number"
        },
        {
            "name": "liquidity_id",
            "baseName": "liquidity_id",
            "type": "string"
        },
        {
            "name": "seller_status",
            "baseName": "seller_status",
            "type": "string"
        },
        {
            "name": "liquidity_settlement_hash",
            "baseName": "liquidity_settlement_hash",
            "type": "string"
        },
        {
            "name": "sp_withdrawal_tx_hash",
            "baseName": "sp_withdrawal_tx_hash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RFQDocumentUpdate.attributeTypeMap;
    }
}


