/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Quote } from './quote';
import { RFQDocumentFacilitatorValidatorsInner } from './rFQDocumentFacilitatorValidatorsInner';

export class RFQDocumentFacilitator {
   'id': string;
   'status': RFQDocumentFacilitator.statusEnum;
   'total_balance': number;
   'payment_address': string;
   'validators': Array<RFQDocumentFacilitatorValidatorsInner>;
   'quotes'?: Array<Quote>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RFQDocumentFacilitator.statusEnum"
        },
        {
            "name": "total_balance",
            "baseName": "total_balance",
            "type": "number"
        },
        {
            "name": "payment_address",
            "baseName": "payment_address",
            "type": "string"
        },
        {
            "name": "validators",
            "baseName": "validators",
            "type": "Array<RFQDocumentFacilitatorValidatorsInner>"
        },
        {
            "name": "quotes",
            "baseName": "quotes",
            "type": "Array<Quote>"
        }    ];

    static getAttributeTypeMap() {
        return RFQDocumentFacilitator.attributeTypeMap;
    }
}

export namespace RFQDocumentFacilitator {
/**
* 
*/
export type statusEnum = 
'active' | 
'expired' | 
'rejected' | 
'finished' | 
'failed';
}

