/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class RFQDocumentFacilitatorValidatorsInner {
   'validator_index'?: number;
   'balance'?: number;
   'exit_estimate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validator_index",
            "baseName": "validator_index",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "exit_estimate",
            "baseName": "exit_estimate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return RFQDocumentFacilitatorValidatorsInner.attributeTypeMap;
    }
}


