/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class RoleAssignment {
    /**
    * Role name (dashboard, pool, or withdrawal queue role)
    */
   'role': RoleAssignment.roleEnum;
    /**
    * Ethereum address to grant or revoke the role for
    */
   'account': string;
    /**
    * Which contract the role belongs to. Defaults to \'dashboard\'. Use \'pool\' for pool-specific roles (DEPOSITS_PAUSE_ROLE, DEPOSITS_RESUME_ROLE, etc.). Use \'withdrawalQueue\' for withdrawal queue roles (WITHDRAWALS_PAUSE_ROLE, WITHDRAWALS_RESUME_ROLE, FINALIZE_PAUSE_ROLE, FINALIZE_RESUME_ROLE, FINALIZE_ROLE). 
    */
   'target'?: RoleAssignment.targetEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "role",
            "baseName": "role",
            "type": "RoleAssignment.roleEnum"
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "RoleAssignment.targetEnum"
        }    ];

    static getAttributeTypeMap() {
        return RoleAssignment.attributeTypeMap;
    }
}

export namespace RoleAssignment {
/**
* Role name (dashboard, pool, or withdrawal queue role)
*/
export type roleEnum = 
'BURN_ROLE' | 
'COLLECT_VAULT_ERC20_ROLE' | 
'DEFAULT_ADMIN_ROLE' | 
'FUND_ROLE' | 
'MINT_ROLE' | 
'NODE_OPERATOR_FEE_EXEMPT_ROLE' | 
'NODE_OPERATOR_MANAGER_ROLE' | 
'NODE_OPERATOR_PROVE_UNKNOWN_VALIDATOR_ROLE' | 
'NODE_OPERATOR_UNGUARANTEED_DEPOSIT_ROLE' | 
'PAUSE_BEACON_CHAIN_DEPOSITS_ROLE' | 
'REBALANCE_ROLE' | 
'REQUEST_VALIDATOR_EXIT_ROLE' | 
'RESUME_BEACON_CHAIN_DEPOSITS_ROLE' | 
'TRIGGER_VALIDATOR_WITHDRAWAL_ROLE' | 
'WITHDRAW_ROLE' | 
'DEPOSITS_PAUSE_ROLE' | 
'DEPOSITS_RESUME_ROLE' | 
'ALLOW_LIST_MANAGER_ROLE' | 
'LOSS_SOCIALIZER_ROLE' | 
'MINTING_PAUSE_ROLE' | 
'MINTING_RESUME_ROLE' | 
'WITHDRAWALS_PAUSE_ROLE' | 
'WITHDRAWALS_RESUME_ROLE' | 
'FINALIZE_PAUSE_ROLE' | 
'FINALIZE_RESUME_ROLE' | 
'FINALIZE_ROLE';
/**
* Which contract the role belongs to. Defaults to \'dashboard\'. Use \'pool\' for pool-specific roles (DEPOSITS_PAUSE_ROLE, DEPOSITS_RESUME_ROLE, etc.). Use \'withdrawalQueue\' for withdrawal queue roles (WITHDRAWALS_PAUSE_ROLE, WITHDRAWALS_RESUME_ROLE, FINALIZE_PAUSE_ROLE, FINALIZE_RESUME_ROLE, FINALIZE_ROLE). 
*/
export type targetEnum = 
'dashboard' | 
'pool' | 
'withdrawalQueue';
}

