/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AcceptedQuote } from './acceptedQuote';
import { EscrowPayment } from './escrowPayment';
import { EscrowReleased } from './escrowReleased';
import { ExitProposal } from './exitProposal';
import { WithdrawalClaimable } from './withdrawalClaimable';
import { WithdrawalRecipientSettlement } from './withdrawalRecipientSettlement';

export class SettlementSteps {
   'accepted_quote'?: AcceptedQuote;
   'escrow_payment'?: EscrowPayment;
   'withdrawal_recipient_settlement'?: WithdrawalRecipientSettlement;
   'escrow_released'?: EscrowReleased;
   'exit_proposal'?: ExitProposal;
   'withdrawals_claimable'?: Array<WithdrawalClaimable>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accepted_quote",
            "baseName": "accepted_quote",
            "type": "AcceptedQuote"
        },
        {
            "name": "escrow_payment",
            "baseName": "escrow_payment",
            "type": "EscrowPayment"
        },
        {
            "name": "withdrawal_recipient_settlement",
            "baseName": "withdrawal_recipient_settlement",
            "type": "WithdrawalRecipientSettlement"
        },
        {
            "name": "escrow_released",
            "baseName": "escrow_released",
            "type": "EscrowReleased"
        },
        {
            "name": "exit_proposal",
            "baseName": "exit_proposal",
            "type": "ExitProposal"
        },
        {
            "name": "withdrawals_claimable",
            "baseName": "withdrawals_claimable",
            "type": "Array<WithdrawalClaimable>"
        }    ];

    static getAttributeTypeMap() {
        return SettlementSteps.attributeTypeMap;
    }
}


