/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Asset } from './asset';

/**
* General info about a smart contract
*/
export class SmartContract {
   'name': string;
   'asset': Asset;
   'address': string;
   'type'?: string;
   'deployedAt': Date;
   'deployedBy'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "Asset"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "deployedAt",
            "baseName": "deployedAt",
            "type": "Date"
        },
        {
            "name": "deployedBy",
            "baseName": "deployedBy",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SmartContract.attributeTypeMap;
    }
}

export namespace SmartContract {
}

