/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StakeEthResponse } from './stakeEthResponse';
import { StakingRequestStatus } from './stakingRequestStatus';

export class StakingRequest {
   'stakeEthResponse'?: StakeEthResponse;
    /**
    * Amount of ETH to stake
    */
   'amount'?: string;
   'status': StakingRequestStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stakeEthResponse",
            "baseName": "stakeEthResponse",
            "type": "StakeEthResponse"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StakingRequestStatus"
        }    ];

    static getAttributeTypeMap() {
        return StakingRequest.attributeTypeMap;
    }
}

export namespace StakingRequest {
}

