/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StakeEthResponseDestructuredCallDataInner } from './stakeEthResponseDestructuredCallDataInner';

export class StakeEthResponse {
   'callData'?: string;
    /**
    * Address of the dashboard contract
    */
   'dashboardAddress'?: string;
   'destructuredCallData'?: Array<StakeEthResponseDestructuredCallDataInner>;
   'stakingRequestId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "callData",
            "baseName": "callData",
            "type": "string"
        },
        {
            "name": "dashboardAddress",
            "baseName": "dashboardAddress",
            "type": "string"
        },
        {
            "name": "destructuredCallData",
            "baseName": "destructuredCallData",
            "type": "Array<StakeEthResponseDestructuredCallDataInner>"
        },
        {
            "name": "stakingRequestId",
            "baseName": "stakingRequestId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StakeEthResponse.attributeTypeMap;
    }
}


