/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class StakeEthResponseDestructuredCallDataInner {
    /**
    * Public key of the validator
    */
   'pubkey'?: string;
    /**
    * Signature of the validator
    */
   'signature'?: string;
    /**
    * Deposit data root of the validator
    */
   'depositDataRoot'?: string;
    /**
    * Amount to stake in wei
    */
   'amount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pubkey",
            "baseName": "pubkey",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "depositDataRoot",
            "baseName": "depositDataRoot",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StakeEthResponseDestructuredCallDataInner.attributeTypeMap;
    }
}


