/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TimelockOperationItem {
    /**
    * The operation ID (keccak256 hash).
    */
   'id': string;
    /**
    * The contracts ID this operation belongs to.
    */
   'contractId': string;
    /**
    * The timelock controller contract address.
    */
   'timelockAddress': string;
    /**
    * The target contract address for the operation.
    */
   'target': string;
    /**
    * The ETH value to send with the operation (wei string).
    */
   'value': string;
    /**
    * The encoded calldata for the operation.
    */
   'calldata': string;
    /**
    * The random salt used for this operation.
    */
   'salt': string;
    /**
    * The predecessor operation ID (zero hash if none).
    */
   'predecessor': string;
    /**
    * The delay in seconds before execution is allowed (bigint string).
    */
   'delay': string;
    /**
    * ISO timestamp when the operation was scheduled.
    */
   'scheduledAt': string;
    /**
    * ISO timestamp after which the operation can be executed.
    */
   'executeAfter': string;
    /**
    * Current status of the operation.
    */
   'status': TimelockOperationItem.statusEnum;
    /**
    * Decoded function name from the calldata (e.g. \"grantRole\"). Only present when the calldata could be decoded.
    */
   'decodedFunction'?: string;
    /**
    * Full function signature (e.g. \"grantRole(bytes32,address)\"). Only present when the calldata could be decoded.
    */
   'decodedSignature'?: string;
    /**
    * Decoded function arguments as key-value pairs. Only present when the calldata could be decoded.
    */
   'decodedArgs'?: { [key: string]: any; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "contractId",
            "baseName": "contractId",
            "type": "string"
        },
        {
            "name": "timelockAddress",
            "baseName": "timelockAddress",
            "type": "string"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "calldata",
            "baseName": "calldata",
            "type": "string"
        },
        {
            "name": "salt",
            "baseName": "salt",
            "type": "string"
        },
        {
            "name": "predecessor",
            "baseName": "predecessor",
            "type": "string"
        },
        {
            "name": "delay",
            "baseName": "delay",
            "type": "string"
        },
        {
            "name": "scheduledAt",
            "baseName": "scheduledAt",
            "type": "string"
        },
        {
            "name": "executeAfter",
            "baseName": "executeAfter",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TimelockOperationItem.statusEnum"
        },
        {
            "name": "decodedFunction",
            "baseName": "decodedFunction",
            "type": "string"
        },
        {
            "name": "decodedSignature",
            "baseName": "decodedSignature",
            "type": "string"
        },
        {
            "name": "decodedArgs",
            "baseName": "decodedArgs",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return TimelockOperationItem.attributeTypeMap;
    }
}

export namespace TimelockOperationItem {
/**
* Current status of the operation.
*/
export type statusEnum = 
'pending' | 
'ready' | 
'executed' | 
'cancelled';
}

