/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Supported transaction types.
*/
export type TransactionEventType = 
'stake' | 
'unstake' | 
'withdrawal' | 
'deposit' | 
'reward';

