/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Asset } from './asset';
import { TransactionEventType } from './transactionEventType';

/**
* Details of transactions including type, amount, and asset.
*/
export class Transaction {
    /**
    * The date and time when the transaction occurred.
    */
   'eventTime': Date;
   'eventType': TransactionEventType;
    /**
    * Asset amount involved in the transaction.
    */
   'assetAmount': number;
   'asset': Asset;
    /**
    * Unique identifier for the order associated with the transaction.
    */
   'orderId'?: string;
    /**
    * Unique identifier for the transaction.
    */
   'eventId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventTime",
            "baseName": "eventTime",
            "type": "Date"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "TransactionEventType"
        },
        {
            "name": "assetAmount",
            "baseName": "assetAmount",
            "type": "number"
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "Asset"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }
}

export namespace Transaction {
}

