/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InternalTransaction } from './internalTransaction';

export class Transaction {
   'blockNumber': number;
   'timeStamp': Date;
   'hash': string;
   'nonce'?: number;
   'blockHash'?: string;
   'transactionIndex'?: number;
   'fromAddress': string;
   'toAddress': string;
    /**
    * Transaction value in eth
    */
   'value': string;
    /**
    * Transaction value in USD
    */
   'valueInUSD'?: string;
    /**
    * Gas price in gwei per unit
    */
   'gasPrice'?: string;
    /**
    * amount of gas used
    */
   'gasUsed'?: string;
    /**
    * Transaction fee in eth (gasPrice * gasUsed)
    */
   'transactionFee'?: string;
    /**
    * Transaction fee in USD
    */
   'transactionFeeInUSD'?: string;
    /**
    * Whether the transaction failed or not
    */
   'isError'?: boolean;
    /**
    * Transaction input data in hex
    */
   'input'?: string;
    /**
    * Decoded transaction input data
    */
   'inputDecoded'?: object;
    /**
    * The name of the function called in the transaction
    */
   'functionName'?: string;
    /**
    * The signature of the function called in the transaction
    */
   'functionSignature'?: string;
    /**
    * Decoded arguments passed to the function called in the transaction including argument names, types, and values
    */
   'functionArgsDecoded'?: object;
    /**
    * The inferred amount from function arguments in human-readable format (e.g., \"1.5\" for 1.5 ETH)
    */
   'inferredAmount'?: string | null;
    /**
    * The currency/token type of the inferred amount (e.g., ETH, STETH, WSTETH, SHARES)
    */
   'inferredCurrency'?: string | null;
    /**
    * The unique identifier of the staking vault contract associated with this transaction
    */
   'stakingVaultContractId': string;
   'internalTransactions'?: Array<InternalTransaction>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockNumber",
            "baseName": "blockNumber",
            "type": "number"
        },
        {
            "name": "timeStamp",
            "baseName": "timeStamp",
            "type": "Date"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "number"
        },
        {
            "name": "blockHash",
            "baseName": "blockHash",
            "type": "string"
        },
        {
            "name": "transactionIndex",
            "baseName": "transactionIndex",
            "type": "number"
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string"
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "valueInUSD",
            "baseName": "valueInUSD",
            "type": "string"
        },
        {
            "name": "gasPrice",
            "baseName": "gasPrice",
            "type": "string"
        },
        {
            "name": "gasUsed",
            "baseName": "gasUsed",
            "type": "string"
        },
        {
            "name": "transactionFee",
            "baseName": "transactionFee",
            "type": "string"
        },
        {
            "name": "transactionFeeInUSD",
            "baseName": "transactionFeeInUSD",
            "type": "string"
        },
        {
            "name": "isError",
            "baseName": "isError",
            "type": "boolean"
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "string"
        },
        {
            "name": "inputDecoded",
            "baseName": "inputDecoded",
            "type": "object"
        },
        {
            "name": "functionName",
            "baseName": "functionName",
            "type": "string"
        },
        {
            "name": "functionSignature",
            "baseName": "functionSignature",
            "type": "string"
        },
        {
            "name": "functionArgsDecoded",
            "baseName": "functionArgsDecoded",
            "type": "object"
        },
        {
            "name": "inferredAmount",
            "baseName": "inferredAmount",
            "type": "string"
        },
        {
            "name": "inferredCurrency",
            "baseName": "inferredCurrency",
            "type": "string"
        },
        {
            "name": "stakingVaultContractId",
            "baseName": "stakingVaultContractId",
            "type": "string"
        },
        {
            "name": "internalTransactions",
            "baseName": "internalTransactions",
            "type": "Array<InternalTransaction>"
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }
}


