/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Specifies the status of the unstaking process.
*/
export type UnstakeStepType = 
'unstake_transaction_requested' | 
'unstake_transaction_submitted' | 
'unstake_transaction_finalized' | 
'transfer_to_liquid_submitted' | 
'transfer_to_liquid_finalized' | 
'standardized' | 
'postgres_registered_unstake' | 
'postgres_registered_release' | 
'done' | 
'reward_transfer_submitted' | 
'reward_transfer_finalized' | 
'withdrawal_transaction_submitted' | 
'withdrawal_transaction_finalized' | 
'rewards_distributed';

