/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidatorProvider } from './validatorProvider';

/**
* Daily reward summary for a specific validator
*/
export class ValidatorDailyReward {
    /**
    * Validator index
    */
   'validator_index': number;
    /**
    * Validator public key (48 bytes, 96 hex characters)
    */
   'validator_public_key': string;
    /**
    * Total rewards earned by this validator on this date in ETH
    */
   'total_rewards_eth': string;
    /**
    * Consensus rewards in ETH
    */
   'consensus_rewards_eth': string;
    /**
    * Block proposal rewards in ETH
    */
   'block_rewards_eth': string;
    /**
    * MEV rewards in ETH
    */
   'mev_rewards_eth': string;
    /**
    * Number of blocks proposed on this date
    */
   'blocks_proposed': number;
    /**
    * Attestation efficiency percentage for this date
    */
   'attestation_efficiency': number;
   'staking_provider'?: ValidatorProvider;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validator_index",
            "baseName": "validator_index",
            "type": "number"
        },
        {
            "name": "validator_public_key",
            "baseName": "validator_public_key",
            "type": "string"
        },
        {
            "name": "total_rewards_eth",
            "baseName": "total_rewards_eth",
            "type": "string"
        },
        {
            "name": "consensus_rewards_eth",
            "baseName": "consensus_rewards_eth",
            "type": "string"
        },
        {
            "name": "block_rewards_eth",
            "baseName": "block_rewards_eth",
            "type": "string"
        },
        {
            "name": "mev_rewards_eth",
            "baseName": "mev_rewards_eth",
            "type": "string"
        },
        {
            "name": "blocks_proposed",
            "baseName": "blocks_proposed",
            "type": "number"
        },
        {
            "name": "attestation_efficiency",
            "baseName": "attestation_efficiency",
            "type": "number"
        },
        {
            "name": "staking_provider",
            "baseName": "staking_provider",
            "type": "ValidatorProvider"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorDailyReward.attributeTypeMap;
    }
}

export namespace ValidatorDailyReward {
}

