/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidatorProvider } from './validatorProvider';

/**
* Information about a blockchain validator including status and balance.
*/
export class ValidatorInfo {
    /**
    * Balance of the validator in ETH
    */
   'balance'?: string;
    /**
    * Effective balance of the validator in ETH
    */
   'effectiveBalance'?: string;
    /**
    * Validator asset
    */
   'asset'?: ValidatorInfo.assetEnum;
   'validatorPublicKey'?: string;
   'validatorIndex'?: number;
    /**
    * Status of the validator on the network
    */
   'status'?: ValidatorInfo.statusEnum;
   'stakingProvider'?: ValidatorProvider;
   'stakingVaultId'?: string;
   'pdgState'?: ValidatorInfo.pdgStateEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "effectiveBalance",
            "baseName": "effectiveBalance",
            "type": "string"
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "ValidatorInfo.assetEnum"
        },
        {
            "name": "validatorPublicKey",
            "baseName": "validatorPublicKey",
            "type": "string"
        },
        {
            "name": "validatorIndex",
            "baseName": "validatorIndex",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ValidatorInfo.statusEnum"
        },
        {
            "name": "stakingProvider",
            "baseName": "stakingProvider",
            "type": "ValidatorProvider"
        },
        {
            "name": "stakingVaultId",
            "baseName": "stakingVaultId",
            "type": "string"
        },
        {
            "name": "pdgState",
            "baseName": "pdgState",
            "type": "ValidatorInfo.pdgStateEnum"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorInfo.attributeTypeMap;
    }
}

export namespace ValidatorInfo {
/**
* Validator asset
*/
export type assetEnum = 
'ETH';
/**
* Status of the validator on the network
*/
export type statusEnum = 
'activating' | 
'active' | 
'exiting' | 
'exited' | 
'sold';
/**
* 
*/
export type pdgStateEnum = 
'predeposited' | 
'proven' | 
'activated' | 
'compensated' | 
'unknown_to_pdg';
}

