/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ValidateConsolidationRequestsResponseConsolidationDetailsInner {
    /**
    * Source validator public key
    */
   'sourcePubKey'?: string;
    /**
    * Current balance of the source validator (in wei)
    */
   'sourcePubKeyBalance'?: string;
    /**
    * Target validator public key
    */
   'targetPubKey'?: string;
    /**
    * Current balance of the target validator (in wei)
    */
   'targetPubKeyBalance'?: string;
    /**
    * Projected balance of target validator after consolidation (in wei)
    */
   'targetPubKeyConsolidatedBalance'?: string;
    /**
    * Wallet address that can sign the consolidation transaction
    */
   'signingWalletAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sourcePubKey",
            "baseName": "sourcePubKey",
            "type": "string"
        },
        {
            "name": "sourcePubKeyBalance",
            "baseName": "sourcePubKeyBalance",
            "type": "string"
        },
        {
            "name": "targetPubKey",
            "baseName": "targetPubKey",
            "type": "string"
        },
        {
            "name": "targetPubKeyBalance",
            "baseName": "targetPubKeyBalance",
            "type": "string"
        },
        {
            "name": "targetPubKeyConsolidatedBalance",
            "baseName": "targetPubKeyConsolidatedBalance",
            "type": "string"
        },
        {
            "name": "signingWalletAddress",
            "baseName": "signingWalletAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidateConsolidationRequestsResponseConsolidationDetailsInner.attributeTypeMap;
    }
}


