/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExitEstimateSeller } from './exitEstimateSeller';
import { ValidatorKeyHolder } from './validatorKeyHolder';
import { ValidatorType } from './validatorType';

/**
* Information about a blockchain validator including status and balance.
*/
export class ValidatorInfo {
   'balance'?: number;
    /**
    * Validator asset
    */
   'asset'?: ValidatorInfo.assetEnum;
   'validator_public_key'?: string;
   'validator_index'?: number;
    /**
    * Status of the validator on the network
    */
   'status'?: ValidatorInfo.statusEnum;
   'exit_estimate'?: ExitEstimateSeller;
   'key_holder'?: ValidatorKeyHolder;
   'validator_type'?: ValidatorType;
   'contract_address'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "ValidatorInfo.assetEnum"
        },
        {
            "name": "validator_public_key",
            "baseName": "validator_public_key",
            "type": "string"
        },
        {
            "name": "validator_index",
            "baseName": "validator_index",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ValidatorInfo.statusEnum"
        },
        {
            "name": "exit_estimate",
            "baseName": "exit_estimate",
            "type": "ExitEstimateSeller"
        },
        {
            "name": "key_holder",
            "baseName": "key_holder",
            "type": "ValidatorKeyHolder"
        },
        {
            "name": "validator_type",
            "baseName": "validator_type",
            "type": "ValidatorType"
        },
        {
            "name": "contract_address",
            "baseName": "contract_address",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorInfo.attributeTypeMap;
    }
}

export namespace ValidatorInfo {
/**
* Validator asset
*/
export type assetEnum = 
'ETH';
/**
* Status of the validator on the network
*/
export type statusEnum = 
'activating' | 
'active' | 
'exiting' | 
'exited' | 
'sold';
}

