/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidateConsolidationRequestsResponseConsolidationDetailsInner } from './validateConsolidationRequestsResponseConsolidationDetailsInner';

export class ValidateConsolidationRequestsResponse {
    /**
    * Total balance of all source validators being consolidated (in wei)
    */
   'totalConsolidationBalance'?: string;
    /**
    * Array of consolidation details for each source/target pair
    */
   'consolidationDetails'?: Array<ValidateConsolidationRequestsResponseConsolidationDetailsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalConsolidationBalance",
            "baseName": "totalConsolidationBalance",
            "type": "string"
        },
        {
            "name": "consolidationDetails",
            "baseName": "consolidationDetails",
            "type": "Array<ValidateConsolidationRequestsResponseConsolidationDetailsInner>"
        }    ];

    static getAttributeTypeMap() {
        return ValidateConsolidationRequestsResponse.attributeTypeMap;
    }
}


