/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ValidatorWithdrawal {
   'asset': ValidatorWithdrawal.assetEnum;
   'validatorPublicKey': string;
   'validatorIndex': number;
   'epoch': number;
   'slot': number;
   'withdrawalTime': Date;
   'withdrawalIndex': number;
   'withdrawalAddress': string;
   'amount': string;
    /**
    * Withdrawal amount in USD
    */
   'amountInUSD'?: string;
   'withdrawalType': ValidatorWithdrawal.withdrawalTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "ValidatorWithdrawal.assetEnum"
        },
        {
            "name": "validatorPublicKey",
            "baseName": "validatorPublicKey",
            "type": "string"
        },
        {
            "name": "validatorIndex",
            "baseName": "validatorIndex",
            "type": "number"
        },
        {
            "name": "epoch",
            "baseName": "epoch",
            "type": "number"
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "number"
        },
        {
            "name": "withdrawalTime",
            "baseName": "withdrawalTime",
            "type": "Date"
        },
        {
            "name": "withdrawalIndex",
            "baseName": "withdrawalIndex",
            "type": "number"
        },
        {
            "name": "withdrawalAddress",
            "baseName": "withdrawalAddress",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "amountInUSD",
            "baseName": "amountInUSD",
            "type": "string"
        },
        {
            "name": "withdrawalType",
            "baseName": "withdrawalType",
            "type": "ValidatorWithdrawal.withdrawalTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorWithdrawal.attributeTypeMap;
    }
}

export namespace ValidatorWithdrawal {
/**
* 
*/
export type assetEnum = 
'ETH';
/**
* 
*/
export type withdrawalTypeEnum = 
'full' | 
'partial';
}

