/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ValidatorRewardsDaily {
    /**
    * UTC date (YYYY-MM-DD format)
    */
   'date': string;
    /**
    * The unique identifier of the staking vault contract
    */
   'stakingVaultContractId': string;
    /**
    * Type of reward
    */
   'rewardType': ValidatorRewardsDaily.rewardTypeEnum;
    /**
    * Total rewards for this staking vault/type/date in ETH
    */
   'amountEth': string;
    /**
    * Number of validators that received rewards for this staking vault/type/date
    */
   'validatorCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "stakingVaultContractId",
            "baseName": "stakingVaultContractId",
            "type": "string"
        },
        {
            "name": "rewardType",
            "baseName": "rewardType",
            "type": "ValidatorRewardsDaily.rewardTypeEnum"
        },
        {
            "name": "amountEth",
            "baseName": "amountEth",
            "type": "string"
        },
        {
            "name": "validatorCount",
            "baseName": "validatorCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorRewardsDaily.attributeTypeMap;
    }
}

export namespace ValidatorRewardsDaily {
/**
* Type of reward
*/
export type rewardTypeEnum = 
'consensus' | 
'block' | 
'mev';
}

