/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ValidatorWithdrawal {
   'asset': ValidatorWithdrawal.assetEnum;
   'validator_public_key': string;
   'validator_index': number;
   'epoch': number;
   'slot': number;
   'withdrawal_time': Date;
   'withdrawal_index': number;
   'withdrawal_address': string;
   'amount': string;
    /**
    * Withdrawal amount in USD
    */
   'amountInUSD'?: string;
   'withdrawal_type': ValidatorWithdrawal.withdrawalTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "ValidatorWithdrawal.assetEnum"
        },
        {
            "name": "validator_public_key",
            "baseName": "validator_public_key",
            "type": "string"
        },
        {
            "name": "validator_index",
            "baseName": "validator_index",
            "type": "number"
        },
        {
            "name": "epoch",
            "baseName": "epoch",
            "type": "number"
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "number"
        },
        {
            "name": "withdrawal_time",
            "baseName": "withdrawal_time",
            "type": "Date"
        },
        {
            "name": "withdrawal_index",
            "baseName": "withdrawal_index",
            "type": "number"
        },
        {
            "name": "withdrawal_address",
            "baseName": "withdrawal_address",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "amountInUSD",
            "baseName": "amountInUSD",
            "type": "string"
        },
        {
            "name": "withdrawal_type",
            "baseName": "withdrawal_type",
            "type": "ValidatorWithdrawal.withdrawalTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorWithdrawal.attributeTypeMap;
    }
}

export namespace ValidatorWithdrawal {
/**
* 
*/
export type assetEnum = 
'ETH';
/**
* 
*/
export type withdrawalTypeEnum = 
'full' | 
'partial';
}

