/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Raw validator reward data
*/
export class ValidatorRewardRaw {
    /**
    * Validator index
    */
   'validatorIndex': string;
    /**
    * Validator public key (48 bytes, 96 hex characters)
    */
   'validatorPublicKey': string;
    /**
    * The unique identifier of the staking vault contract associated with this reward
    */
   'stakingVaultContractId': string;
    /**
    * Epoch when the reward was earned
    */
   'epoch': string;
    /**
    * Slot when the reward was earned
    */
   'slot': string;
    /**
    * Block number when the reward was earned
    */
   'blockNumber'?: string;
    /**
    * Timestamp when the reward was earned
    */
   'timestamp': Date;
    /**
    * Type of reward: - consensus: Sum of attestation rewards, sync committee fees, etc. - block: Block proposal rewards - mev: MEV rewards 
    */
   'rewardType': ValidatorRewardRaw.rewardTypeEnum;
    /**
    * Reward amount in ETH
    */
   'amountEth': string;
    /**
    * Transaction hash (if applicable for MEV/block rewards)
    */
   'transactionHash'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validatorIndex",
            "baseName": "validatorIndex",
            "type": "string"
        },
        {
            "name": "validatorPublicKey",
            "baseName": "validatorPublicKey",
            "type": "string"
        },
        {
            "name": "stakingVaultContractId",
            "baseName": "stakingVaultContractId",
            "type": "string"
        },
        {
            "name": "epoch",
            "baseName": "epoch",
            "type": "string"
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "string"
        },
        {
            "name": "blockNumber",
            "baseName": "blockNumber",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "rewardType",
            "baseName": "rewardType",
            "type": "ValidatorRewardRaw.rewardTypeEnum"
        },
        {
            "name": "amountEth",
            "baseName": "amountEth",
            "type": "string"
        },
        {
            "name": "transactionHash",
            "baseName": "transactionHash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorRewardRaw.attributeTypeMap;
    }
}

export namespace ValidatorRewardRaw {
/**
* Type of reward: - consensus: Sum of attestation rewards, sync committee fees, etc. - block: Block proposal rewards - mev: MEV rewards 
*/
export type rewardTypeEnum = 
'consensus' | 
'block' | 
'mev';
}

