/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderUpdatePayload } from './orderUpdatePayload';
import { RFQUpdatePayload } from './rFQUpdatePayload';

/**
* The payload data specific to the event type.
*/
export class WebhookPayloadData {
    /**
    * Unique identifier for the updated order.
    */
   'orderId'?: string;
    /**
    * New status of the RFQ.
    */
   'status'?: string;
    /**
    * Additional details regarding the order update.
    */
   'details'?: object;
    /**
    * Unique identifier for the RFQ.
    */
   'rfqId'?: string;
    /**
    * The best quote for the RFQ, if available.
    */
   'bestQuote'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "object"
        },
        {
            "name": "rfqId",
            "baseName": "rfqId",
            "type": "string"
        },
        {
            "name": "bestQuote",
            "baseName": "bestQuote",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WebhookPayloadData.attributeTypeMap;
    }
}


