/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WebhookPayloadRFQEscrowReleasedDetails {
   'timestamp'?: Date;
   'transaction_hash'?: string;
   'amount'?: number;
   'gas_amount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "transaction_hash",
            "baseName": "transaction_hash",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "gas_amount",
            "baseName": "gas_amount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WebhookPayloadRFQEscrowReleasedDetails.attributeTypeMap;
    }
}


