/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WebhookPayloadRFQValidatorExitedDetails {
   'timestamp'?: Date;
   'validator_index'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "validator_index",
            "baseName": "validator_index",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WebhookPayloadRFQValidatorExitedDetails.attributeTypeMap;
    }
}


