/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationEventType } from './notificationEventType';
import { WebhookEventFundingReceived } from './webhookEventFundingReceived';
import { WebhookEventReportUpdateAvailable } from './webhookEventReportUpdateAvailable';
import { WebhookEventReportUpdateAvailableAllOfData } from './webhookEventReportUpdateAvailableAllOfData';
import { WebhookEventValidatorActivated } from './webhookEventValidatorActivated';
import { WebhookEventValidatorExited } from './webhookEventValidatorExited';
import { WebhookEventValidatorWithdrawalCompleted } from './webhookEventValidatorWithdrawalCompleted';
import { WebhookEventWithdrawalClaimed } from './webhookEventWithdrawalClaimed';

/**
* Body POSTed to your webhook URL when an event fires. Verify authenticity by computing HMAC-SHA256 of the raw request body with your secret token and comparing it to the `X-Northstake-Signature` header (hex-encoded).
*/
export class WebhookDeliveryBody {
   'event_type': NotificationEventType;
   'staking_vault_id': string;
   'message': string;
    /**
    * Unix millisecond timestamp.
    */
   'created_at': number;
   'data': WebhookEventReportUpdateAvailableAllOfData;

    static discriminator: string | undefined = "eventType";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "event_type",
            "baseName": "event_type",
            "type": "NotificationEventType"
        },
        {
            "name": "staking_vault_id",
            "baseName": "staking_vault_id",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "WebhookEventReportUpdateAvailableAllOfData"
        }    ];

    static getAttributeTypeMap() {
        return WebhookDeliveryBody.attributeTypeMap;
    }
}

export namespace WebhookDeliveryBody {
}

