/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WebhookEventFundingReceivedAllOfData {
   'tx_hash': string;
    /**
    * Amount received in Wei.
    */
   'amount_wei': string;
   'staking_vault_address': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tx_hash",
            "baseName": "tx_hash",
            "type": "string"
        },
        {
            "name": "amount_wei",
            "baseName": "amount_wei",
            "type": "string"
        },
        {
            "name": "staking_vault_address",
            "baseName": "staking_vault_address",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WebhookEventFundingReceivedAllOfData.attributeTypeMap;
    }
}


