/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationEventType } from './notificationEventType';

export class Webhook {
   'id': string;
   'url': string;
    /**
    * Event types this webhook subscribes to. Null or absent means all event types.
    */
   'eventTypes'?: Array<NotificationEventType> | null;
    /**
    * Staking vault IDs this webhook filters on. Null or absent means all vaults.
    */
   'stakingVaultIds'?: Array<string> | null;
   'active': boolean;
   'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "eventTypes",
            "baseName": "eventTypes",
            "type": "Array<NotificationEventType>"
        },
        {
            "name": "stakingVaultIds",
            "baseName": "stakingVaultIds",
            "type": "Array<string>"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Webhook.attributeTypeMap;
    }
}


