/**
 * Northstake
 * Northstake api  Operation-level extensions used by the API: - x-roleRequired (array of strings): roles required to call the operation. - x-mfaApiScope (array of strings): MFA API scopes required when the user has MFA enrolled. - x-isProSvmFeature (boolean): when true, the operation is restricted to users whose Cosmos user document has is_pro_svm_user set to true. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WebhookEventWithdrawalRequestedAllOfData {
   'tx_hash': string;
   'request_id': string;
    /**
    * Pool participant who requested the withdrawal
    */
   'owner': string;
    /**
    * STV shares moved to the withdrawal queue (base units)
    */
   'amount_of_stv': string;
    /**
    * stETH shares to rebalance (stvSteth pools; 0 otherwise)
    */
   'amount_of_steth_shares': string;
    /**
    * ETH value of the request at request time (wei)
    */
   'amount_of_assets': string;
    /**
    * amount_of_assets formatted in ETH
    */
   'amount_eth': string;
   'withdrawal_queue_address': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tx_hash",
            "baseName": "tx_hash",
            "type": "string"
        },
        {
            "name": "request_id",
            "baseName": "request_id",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "amount_of_stv",
            "baseName": "amount_of_stv",
            "type": "string"
        },
        {
            "name": "amount_of_steth_shares",
            "baseName": "amount_of_steth_shares",
            "type": "string"
        },
        {
            "name": "amount_of_assets",
            "baseName": "amount_of_assets",
            "type": "string"
        },
        {
            "name": "amount_eth",
            "baseName": "amount_eth",
            "type": "string"
        },
        {
            "name": "withdrawal_queue_address",
            "baseName": "withdrawal_queue_address",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WebhookEventWithdrawalRequestedAllOfData.attributeTypeMap;
    }
}


