/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WithdrawalClaimable {
   'validator_index': number;
   'amount': number;
   'block': number;
   'timestamp': Date;
   'beneficiary_address': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validator_index",
            "baseName": "validator_index",
            "type": "number"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "beneficiary_address",
            "baseName": "beneficiary_address",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WithdrawalClaimable.attributeTypeMap;
    }
}


