/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepStatus } from './stepStatus';
import { WithdrawalStep } from './withdrawalStep';

export class WithdrawalStepElement {
   'steps'?: Array<WithdrawalStep>;
   'status'?: StepStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<WithdrawalStep>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StepStatus"
        }    ];

    static getAttributeTypeMap() {
        return WithdrawalStepElement.attributeTypeMap;
    }
}

export namespace WithdrawalStepElement {
}

