/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Specifies the status of the withdrawal process.
*/
export type WithdrawalStepType = 
'postgres_reserved_tokens' | 
'transferred_to_address' | 
'finalized_withdrawal_transfer' | 
'postgres_registered_withdrawal' | 
'done' | 
'waiting_for_auth';

