// masterApi.mustache
import { JWTAuth } from './model/models';
import { AccountApi } from './api/accountApi';
import { DepositAddressesApi } from './api/depositAddressesApi';
import { LinkedWalletsApi } from './api/linkedWalletsApi';
import { ManagedUsersApi } from './api/managedUsersApi';
import { ManagedUsersDepositAddressesApi } from './api/managedUsersDepositAddressesApi';
import { ManagedUsersLinkedWalletsApi } from './api/managedUsersLinkedWalletsApi';
import { ManagedUsersOrdersApi } from './api/managedUsersOrdersApi';
import { ManagedUsersPortfolioApi } from './api/managedUsersPortfolioApi';
import { ManagedUsersTransactionsApi } from './api/managedUsersTransactionsApi';
import { ManagedUsersValidatorsApi } from './api/managedUsersValidatorsApi';
import { OrdersApi } from './api/ordersApi';
import { PortfolioApi } from './api/portfolioApi';
import { TransactionsApi } from './api/transactionsApi';
import { ValidatorMarketplaceBuyersApi } from './api/validatorMarketplaceBuyersApi';
import { ValidatorMarketplaceSellersApi } from './api/validatorMarketplaceSellersApi';
import { ValidatorMarketplaceWebhooksApi } from './api/validatorMarketplaceWebhooksApi';
import { ValidatorsApi } from './api/validatorsApi';
export * from './model/./acceptedQuote';
export * from './model/./accountEntity';
export * from './model/./addLinkedWalletForUserRequest';
export * from './model/./addLinkedWalletRequest';
export * from './model/./allManagedUsersResponse';
export * from './model/./asset';
export * from './model/./createManagedUserRequest';
export * from './model/./createRFQRequest';
export * from './model/./depositAddress';
export * from './model/./depositAddressesForUserResponse';
export * from './model/./errorResponse';
export * from './model/./escrowPayment';
export * from './model/./escrowReleased';
export * from './model/./ethereumValidatorKey';
export * from './model/./ethereumValidatorKeyKeystore';
export * from './model/./ethereumValidatorKeyKeystoreCrypto';
export * from './model/./ethereumValidatorKeyKeystoreCryptoChecksum';
export * from './model/./ethereumValidatorKeyKeystoreCryptoCipher';
export * from './model/./ethereumValidatorKeyKeystoreCryptoCipherParams';
export * from './model/./ethereumValidatorKeyKeystoreCryptoKdf';
export * from './model/./ethereumValidatorKeyKeystoreCryptoKdfParams';
export * from './model/./exitEstimateBase';
export * from './model/./exitEstimateSeller';
export * from './model/./exitProposal';
export * from './model/./getTransactionsResponse';
export * from './model/./managedUser';
export * from './model/./managedUserDetails';
export * from './model/./order';
export * from './model/./orderDocument';
export * from './model/./orderDocumentSteps';
export * from './model/./orderType';
export * from './model/./orderUpdatePayload';
export * from './model/./portfolioEntity';
export * from './model/./provideEscrowHashForRFQDocumentRequest';
export * from './model/./quote';
export * from './model/./rFQBids';
export * from './model/./rFQDocumentBase';
export * from './model/./rFQDocumentBaseUniqueEscrowVault';
export * from './model/./rFQDocumentBuyer';
export * from './model/./rFQDocumentBuyerAllOfValidators';
export * from './model/./rFQDocumentBuyerStatusFilter';
export * from './model/./rFQDocumentSeller';
export * from './model/./rFQDocumentSellerAllOfValidators';
export * from './model/./rFQDocumentSellerStatusFilter';
export * from './model/./rFQDocumentStatus';
export * from './model/./rFQDocumentUpdate';
export * from './model/./rFQUpdatePayload';
export * from './model/./rFQWebhookEventType';
export * from './model/./registerWithdrawalRecipientSettlementRequest';
export * from './model/./settlementSteps';
export * from './model/./smartContract';
export * from './model/./stakeStep';
export * from './model/./stakeStepElement';
export * from './model/./stepStatus';
export * from './model/./submittedQuote';
export * from './model/./transaction';
export * from './model/./transactionEventType';
export * from './model/./transactionsforUser';
export * from './model/./unstakeStep';
export * from './model/./unstakeStepElement';
export * from './model/./unstakeStepType';
export * from './model/./validatorInfo';
export * from './model/./validatorKeyHolder';
export * from './model/./validatorType';
export * from './model/./wallet';
export * from './model/./webHookLookupAnswer';
export * from './model/./webhookPayload';
export * from './model/./webhookPayloadData';
export * from './model/./webhookPayloadRFQAvailable';
export * from './model/./webhookPayloadRFQBidAccepted';
export * from './model/./webhookPayloadRFQBidAcceptedDetails';
export * from './model/./webhookPayloadRFQBidReceived';
export * from './model/./webhookPayloadRFQBidReceivedDetails';
export * from './model/./webhookPayloadRFQEscrowEvent';
export * from './model/./webhookPayloadRFQEscrowEventDetails';
export * from './model/./webhookPayloadRFQEscrowReleased';
export * from './model/./webhookPayloadRFQEscrowReleasedDetails';
export * from './model/./webhookPayloadRFQTransferProposalReceived';
export * from './model/./webhookPayloadRFQTransferProposalReceivedDetails';
export * from './model/./webhookPayloadRFQValidatorExited';
export * from './model/./webhookPayloadRFQValidatorExitedDetails';
export * from './model/./webhookPayloadRFQValidatorWithdrawalChange';
export * from './model/./webhookPayloadRFQValidatorWithdrawalChangeDetails';
export * from './model/./webhookPayloadRFQWithdrawalClaimable';
export * from './model/./webhookPayloadRFQWithdrawalClaimableDetails';
export * from './model/./webhookRegistration';
export * from './model/./webhookRegistrationDetails';
export * from './model/./withdrawalRecipientSettlement';
export * from './model/./withdrawalStep';
export * from './model/./withdrawalStepElement';
export * from './model/./withdrawalStepType';

export class NorthstakeApi {
    constructor(apiKey: string, privateKey: string, basePath: string = "https://api.northstake.dk/v1") {
        const jwtAuth = new JWTAuth(apiKey, privateKey);

        this.account = new AccountApi(basePath);
        this.account.setDefaultAuthentication(jwtAuth);
        this.depositAddresses = new DepositAddressesApi(basePath);
        this.depositAddresses.setDefaultAuthentication(jwtAuth);
        this.linkedWallets = new LinkedWalletsApi(basePath);
        this.linkedWallets.setDefaultAuthentication(jwtAuth);
        this.managedUsers = new ManagedUsersApi(basePath);
        this.managedUsers.setDefaultAuthentication(jwtAuth);
        this.managedUsersDepositAddresses = new ManagedUsersDepositAddressesApi(basePath);
        this.managedUsersDepositAddresses.setDefaultAuthentication(jwtAuth);
        this.managedUsersLinkedWallets = new ManagedUsersLinkedWalletsApi(basePath);
        this.managedUsersLinkedWallets.setDefaultAuthentication(jwtAuth);
        this.managedUsersOrders = new ManagedUsersOrdersApi(basePath);
        this.managedUsersOrders.setDefaultAuthentication(jwtAuth);
        this.managedUsersPortfolio = new ManagedUsersPortfolioApi(basePath);
        this.managedUsersPortfolio.setDefaultAuthentication(jwtAuth);
        this.managedUsersTransactions = new ManagedUsersTransactionsApi(basePath);
        this.managedUsersTransactions.setDefaultAuthentication(jwtAuth);
        this.managedUsersValidators = new ManagedUsersValidatorsApi(basePath);
        this.managedUsersValidators.setDefaultAuthentication(jwtAuth);
        this.orders = new OrdersApi(basePath);
        this.orders.setDefaultAuthentication(jwtAuth);
        this.portfolio = new PortfolioApi(basePath);
        this.portfolio.setDefaultAuthentication(jwtAuth);
        this.transactions = new TransactionsApi(basePath);
        this.transactions.setDefaultAuthentication(jwtAuth);
        this.validatorMarketplaceBuyers = new ValidatorMarketplaceBuyersApi(basePath);
        this.validatorMarketplaceBuyers.setDefaultAuthentication(jwtAuth);
        this.validatorMarketplaceSellers = new ValidatorMarketplaceSellersApi(basePath);
        this.validatorMarketplaceSellers.setDefaultAuthentication(jwtAuth);
        this.validatorMarketplaceWebhooks = new ValidatorMarketplaceWebhooksApi(basePath);
        this.validatorMarketplaceWebhooks.setDefaultAuthentication(jwtAuth);
        this.validators = new ValidatorsApi(basePath);
        this.validators.setDefaultAuthentication(jwtAuth);
    }
    public account: AccountApi;
    public depositAddresses: DepositAddressesApi;
    public linkedWallets: LinkedWalletsApi;
    public managedUsers: ManagedUsersApi;
    public managedUsersDepositAddresses: ManagedUsersDepositAddressesApi;
    public managedUsersLinkedWallets: ManagedUsersLinkedWalletsApi;
    public managedUsersOrders: ManagedUsersOrdersApi;
    public managedUsersPortfolio: ManagedUsersPortfolioApi;
    public managedUsersTransactions: ManagedUsersTransactionsApi;
    public managedUsersValidators: ManagedUsersValidatorsApi;
    public orders: OrdersApi;
    public portfolio: PortfolioApi;
    public transactions: TransactionsApi;
    public validatorMarketplaceBuyers: ValidatorMarketplaceBuyersApi;
    public validatorMarketplaceSellers: ValidatorMarketplaceSellersApi;
    public validatorMarketplaceWebhooks: ValidatorMarketplaceWebhooksApi;
    public validators: ValidatorsApi;
}


export default NorthstakeApi;