// masterApi.mustache
import { JWTAuth } from './model/models';
import { AccountApi } from './api/accountApi';
import { AccountApiKeysApi } from './api/accountApiKeysApi';
import { LidoReadApi } from './api/lidoReadApi';
import { LidoRewardsApi } from './api/lidoRewardsApi';
import { LidoStakingVaultsApi } from './api/lidoStakingVaultsApi';
import { LidoWriteApi } from './api/lidoWriteApi';
import { LinkedWalletsApi } from './api/linkedWalletsApi';
import { OrganizationApi } from './api/organizationApi';
import { ValidatorsApi } from './api/validatorsApi';
export * from './model/./acceptedQuote';
export * from './model/./accountEntity';
export * from './model/./addLinkedWalletRequest';
export * from './model/./apiKey';
export * from './model/./approveStETH';
export * from './model/./approveWstETH';
export * from './model/./asset';
export * from './model/./burnShares';
export * from './model/./burnStETH';
export * from './model/./burnWstETH';
export * from './model/./changeTier';
export * from './model/./collectERC20FromVault';
export * from './model/./consolidateValidators';
export * from './model/./consolidateValidatorsErrorResponse';
export * from './model/./consolidateValidatorsResponse';
export * from './model/./createLidoStakingContractsRequest';
export * from './model/./createVaultRequest';
export * from './model/./dailyRewardSummaryStats';
export * from './model/./errorResponse';
export * from './model/./errorWithTransactionResponse';
export * from './model/./escrowPayment';
export * from './model/./escrowReleased';
export * from './model/./ethereumValidatorKey';
export * from './model/./ethereumValidatorKeyKeystore';
export * from './model/./ethereumValidatorKeyKeystoreCrypto';
export * from './model/./ethereumValidatorKeyKeystoreCryptoChecksum';
export * from './model/./ethereumValidatorKeyKeystoreCryptoCipher';
export * from './model/./ethereumValidatorKeyKeystoreCryptoCipherParams';
export * from './model/./ethereumValidatorKeyKeystoreCryptoKdf';
export * from './model/./ethereumValidatorKeyKeystoreCryptoKdfParams';
export * from './model/./exitEstimateBase';
export * from './model/./exitEstimateSeller';
export * from './model/./exitProposal';
export * from './model/./fundVault';
export * from './model/./generateApiKeyRequest';
export * from './model/./getLazyOracleReportCallData200Response';
export * from './model/./getLazyOracleReportCallData200ResponseDestructuredCalldata';
export * from './model/./getLazyOracleReportData200Response';
export * from './model/./getLazyOracleReportData200ResponseReportData';
export * from './model/./getLidoTransactions200Response';
export * from './model/./getQuarantineInfo200Response';
export * from './model/./getStETHPerWstETHRate200Response';
export * from './model/./getWithdrawalsResponse';
export * from './model/./grantRole';
export * from './model/./internalTransaction';
export * from './model/./inviteMemberRequest';
export * from './model/./lidoContracts';
export * from './model/./lidoContractsDashboard';
export * from './model/./lidoContractsStakingVault';
export * from './model/./lidoStakingContracts';
export * from './model/./lidoStakingContractsWithData';
export * from './model/./lidoStakingContractsWithDataVaultData';
export * from './model/./mintShares';
export * from './model/./mintStETH';
export * from './model/./mintWstETH';
export * from './model/./organizationMember';
export * from './model/./organizationNameResponse';
export * from './model/./partialTransaction';
export * from './model/./presignedExitKey';
export * from './model/./presignedExitKeyMessage';
export * from './model/./quote';
export * from './model/./rFQBidFacilitator';
export * from './model/./rFQBids';
export * from './model/./rFQDocumentBase';
export * from './model/./rFQDocumentBaseUniqueEscrowVault';
export * from './model/./rFQDocumentBuyer';
export * from './model/./rFQDocumentBuyerAllOfValidators';
export * from './model/./rFQDocumentBuyerStatusFilter';
export * from './model/./rFQDocumentFacilitator';
export * from './model/./rFQDocumentFacilitatorStatusFilter';
export * from './model/./rFQDocumentFacilitatorValidatorsInner';
export * from './model/./rFQDocumentSeller';
export * from './model/./rFQDocumentSellerAllOfValidators';
export * from './model/./rFQDocumentSellerStatusFilter';
export * from './model/./rFQDocumentStatus';
export * from './model/./rFQDocumentUpdate';
export * from './model/./rFQUpdatePayload';
export * from './model/./rFQWebhookEventType';
export * from './model/./rebalanceVaultWithEther';
export * from './model/./rebalanceVaultWithShares';
export * from './model/./recoverERC20';
export * from './model/./renameVaultRequest';
export * from './model/./revokeRole';
export * from './model/./settlementSteps';
export * from './model/./stakeEthRequest';
export * from './model/./stakeEthResponse';
export * from './model/./stakeEthResponseDestructuredCallDataInner';
export * from './model/./stakingRequest';
export * from './model/./stakingRequestStatus';
export * from './model/./supportedValidatorProvidersResponse';
export * from './model/./transaction';
export * from './model/./triggerValidatorWithdrawals';
export * from './model/./unwrapWstETH';
export * from './model/./updateLinkedWalletNameRequest';
export * from './model/./updateMemberRoleRequest';
export * from './model/./updateOrganizationNameRequest';
export * from './model/./updateShareLimit';
export * from './model/./validateConsolidationRequestsResponse';
export * from './model/./validateConsolidationRequestsResponseConsolidationDetailsInner';
export * from './model/./validatorDailyReward';
export * from './model/./validatorInfo';
export * from './model/./validatorKeyHolder';
export * from './model/./validatorProvider';
export * from './model/./validatorRewardRaw';
export * from './model/./validatorRewardsDaily';
export * from './model/./validatorRewardsDailyResponse';
export * from './model/./validatorRewardsRaw';
export * from './model/./validatorType';
export * from './model/./validatorWithdrawal';
export * from './model/./vaultCreationStartResponse';
export * from './model/./wallet';
export * from './model/./webHookLookupAnswer';
export * from './model/./webhookPayload';
export * from './model/./webhookPayloadRFQAvailable';
export * from './model/./webhookPayloadRFQBidAccepted';
export * from './model/./webhookPayloadRFQBidAcceptedDetails';
export * from './model/./webhookPayloadRFQBidReceived';
export * from './model/./webhookPayloadRFQBidReceivedDetails';
export * from './model/./webhookPayloadRFQEscrowEvent';
export * from './model/./webhookPayloadRFQEscrowEventDetails';
export * from './model/./webhookPayloadRFQEscrowReleased';
export * from './model/./webhookPayloadRFQEscrowReleasedDetails';
export * from './model/./webhookPayloadRFQTransferProposalReceived';
export * from './model/./webhookPayloadRFQTransferProposalReceivedDetails';
export * from './model/./webhookPayloadRFQValidatorExited';
export * from './model/./webhookPayloadRFQValidatorExitedDetails';
export * from './model/./webhookPayloadRFQValidatorWithdrawalChange';
export * from './model/./webhookPayloadRFQValidatorWithdrawalChangeDetails';
export * from './model/./webhookPayloadRFQWithdrawalClaimable';
export * from './model/./webhookPayloadRFQWithdrawalClaimableDetails';
export * from './model/./webhookRegistration';
export * from './model/./webhookRegistrationDetails';
export * from './model/./withdrawFromVault';
export * from './model/./withdrawalClaimable';
export * from './model/./withdrawalRecipientSettlement';
export * from './model/./wrapStETH';

export class NorthstakeApi {
    constructor(apiKey: string, privateKey: string, basePath: string = "https://api.northstake.dk/v1") {
        const jwtAuth = new JWTAuth(apiKey, privateKey);

        this.account = new AccountApi(basePath);
        this.account.setDefaultAuthentication(jwtAuth);
        this.accountApiKeys = new AccountApiKeysApi(basePath);
        this.accountApiKeys.setDefaultAuthentication(jwtAuth);
        this.lidoRead = new LidoReadApi(basePath);
        this.lidoRead.setDefaultAuthentication(jwtAuth);
        this.lidoRewards = new LidoRewardsApi(basePath);
        this.lidoRewards.setDefaultAuthentication(jwtAuth);
        this.lidoStakingVaults = new LidoStakingVaultsApi(basePath);
        this.lidoStakingVaults.setDefaultAuthentication(jwtAuth);
        this.lidoWrite = new LidoWriteApi(basePath);
        this.lidoWrite.setDefaultAuthentication(jwtAuth);
        this.linkedWallets = new LinkedWalletsApi(basePath);
        this.linkedWallets.setDefaultAuthentication(jwtAuth);
        this.organization = new OrganizationApi(basePath);
        this.organization.setDefaultAuthentication(jwtAuth);
        this.validators = new ValidatorsApi(basePath);
        this.validators.setDefaultAuthentication(jwtAuth);
    }
    public account: AccountApi;
    public accountApiKeys: AccountApiKeysApi;
    public lidoRead: LidoReadApi;
    public lidoRewards: LidoRewardsApi;
    public lidoStakingVaults: LidoStakingVaultsApi;
    public lidoWrite: LidoWriteApi;
    public linkedWallets: LinkedWalletsApi;
    public organization: OrganizationApi;
    public validators: ValidatorsApi;
}


export default NorthstakeApi;