/**
 * Northstake
 * Northstake api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { ErrorResponse } from '../model/errorResponse';
import { ProvideEscrowHashForRFQDocumentRequest } from '../model/provideEscrowHashForRFQDocumentRequest';
import { RFQDocumentBuyer } from '../model/rFQDocumentBuyer';
import { RFQDocumentBuyerStatusFilter } from '../model/rFQDocumentBuyerStatusFilter';
import { SubmittedQuote } from '../model/submittedQuote';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth, JWTAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.northstake.dk/v1';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum ValidatorMarketplaceBuyersApiApiKeys {
    ApiKeyAuth,
}



export class ValidatorMarketplaceBuyersApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new JWTAuth('your_api_key', 'your_private_key'),
        'bearerTokenAuth': new HttpBearerAuth(),
        'ApiKeyAuth': new ApiKeyAuth('header', 'x-api-key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: ValidatorMarketplaceBuyersApiApiKeys, value: string) {
        (this.authentications as any)[ValidatorMarketplaceBuyersApiApiKeys[key]].apiKey = value;
    }

    set accessToken(accessToken: string | (() => string)) {
        this.authentications.bearerTokenAuth.accessToken = accessToken;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * 
     * @summary Retrieve a specific RFQ
     * @param rfqId 
     */

   



   public async getRFQDocumentForBuyer (rfqId: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ body: RFQDocumentBuyer, status: number }> {

        const localVarPath = this.basePath + '/validatorMarketplace/buyers/documents/{rfqId}'
            .replace('{' + 'rfqId' + '}', encodeURIComponent(String(rfqId)));
       
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};


        // Verify required parameter 'rfqId' is not null or undefined
        if (rfqId === null || rfqId === undefined) {
            throw new Error('Required parameter "rfqId" was null or undefined when calling getRFQDocumentForBuyer.');
        }







        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;



        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
                 return new Promise<{ body: RFQDocumentBuyer, status: number }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    console.error('API call error:', error);
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        body = ObjectSerializer.deserialize(body, "RFQDocumentBuyer");
                        resolve({ body: body, status: response.statusCode });
                    } else {
                        console.error('API response error:', response.statusCode);
                        resolve({ body: body, status: response.statusCode });
                    }
                }
            });
        });
    } )
}
    /**
     * 
     * @summary List RFQs
     * @param status Filter by RFQ status
     */

   



   public async listRFQDocumentsForBuyer (status?: RFQDocumentBuyerStatusFilter, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ body: Array<RFQDocumentBuyer>, status: number }> {

        const localVarPath = this.basePath + '/validatorMarketplace/buyers/documents';
       
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};





    if (status !== undefined) {
        localVarQueryParameters['status'] = ObjectSerializer.serialize(status, "RFQDocumentBuyerStatusFilter");
    }




        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;



        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
                 return new Promise<{ body: Array<RFQDocumentBuyer>, status: number }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    console.error('API call error:', error);
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        body = ObjectSerializer.deserialize(body, "Array<RFQDocumentBuyer>");
                        resolve({ body: body, status: response.statusCode });
                    } else {
                        console.error('API response error:', response.statusCode);
                        resolve({ body: body, status: response.statusCode });
                    }
                }
            });
        });
    } )
}
    /**
     * 
     * @summary Provide a transaction hash for an escrow deposit as part of settlement
     * @param rfqId 
     * @param provideEscrowHashForRFQDocumentRequest 
     */

   



   public async provideEscrowHashForRFQDocument (rfqId: string, provideEscrowHashForRFQDocumentRequest: ProvideEscrowHashForRFQDocumentRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ body: any, status: number }> {

        const localVarPath = this.basePath + '/validatorMarketplace/buyers/documents/{rfqId}/provideEscrowHash'
            .replace('{' + 'rfqId' + '}', encodeURIComponent(String(rfqId)));
       
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};


        // Verify required parameter 'rfqId' is not null or undefined
        if (rfqId === null || rfqId === undefined) {
            throw new Error('Required parameter "rfqId" was null or undefined when calling provideEscrowHashForRFQDocument.');
        }
        // Verify required parameter 'provideEscrowHashForRFQDocumentRequest' is not null or undefined
        if (provideEscrowHashForRFQDocumentRequest === null || provideEscrowHashForRFQDocumentRequest === undefined) {
            throw new Error('Required parameter "provideEscrowHashForRFQDocumentRequest" was null or undefined when calling provideEscrowHashForRFQDocument.');
        }







        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;



        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PATCH',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(provideEscrowHashForRFQDocumentRequest, "ProvideEscrowHashForRFQDocumentRequest")
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
                 return new Promise<{ body: any, status: number }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    console.error('API call error:', error);
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ body: body, status: response.statusCode });
                    } else {
                        console.error('API response error:', response.statusCode);
                        resolve({ body: body, status: response.statusCode });
                    }
                }
            });
        });
    } )
}
    /**
     * 
     * @summary Submit a quote for an RFQ in ETH
     * @param rfqId 
     * @param submittedQuote 
     */

   



   public async submitQuote (rfqId: string, submittedQuote: SubmittedQuote, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ body: any, status: number }> {

        const localVarPath = this.basePath + '/validatorMarketplace/buyers/quotes/{rfqId}/submitQuote'
            .replace('{' + 'rfqId' + '}', encodeURIComponent(String(rfqId)));
       
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};


        // Verify required parameter 'rfqId' is not null or undefined
        if (rfqId === null || rfqId === undefined) {
            throw new Error('Required parameter "rfqId" was null or undefined when calling submitQuote.');
        }
        // Verify required parameter 'submittedQuote' is not null or undefined
        if (submittedQuote === null || submittedQuote === undefined) {
            throw new Error('Required parameter "submittedQuote" was null or undefined when calling submitQuote.');
        }







        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;



        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PATCH',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(submittedQuote, "SubmittedQuote")
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
                 return new Promise<{ body: any, status: number }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    console.error('API call error:', error);
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ body: body, status: response.statusCode });
                    } else {
                        console.error('API response error:', response.statusCode);
                        resolve({ body: body, status: response.statusCode });
                    }
                }
            });
        });
    } )
}
}
